M = {
"Cinematic Brand Film (TV-Style Spot)": ["Cinematic Studio Commercial","Cinematic Mood Film","Cinematic Lifestyle Spot","Cinematic Brand Spot (Feature Supers)","Cinematic Hero Film (TV-Spot Style)","Cinematic Macro Product Film","CGI Product Hero Reel","3D Render Feature Tour","AI Fantasy Product Render","Scent Still-Life Practical FX"],
"Collection Lookbook Reel": ["Editorial Lookbook Film","Collection Lookbook Reel","Studio Fashion Editorial","Aspirational Moment Montage"],
"Brand Anthem Montage (Manifesto)": ["Brand Anthem Montage"],
"Cinematic Mini-Film (Brand Short Story)": ["Cinematic Mini-Film (Brand Short)","Poetry Film (Spoken-Word Mood Piece)"],
"Motion-Graphic Packshot (Animated Static)": ["Animated Packshot Callouts","Motion-Graphic Packshot","Animated Static (Motion Banner)","Animated Product Poster (Moving Static)","Animated Callout Static","Motion-Graphic Promo Card","Motion Poster Announcement (Drop / Restock / Sale)","Handwritten Sign Reveal"],
"Catalog Drop Slideshow": ["Catalog Drop Slideshow","Collection Lookbook Slideshow"],
"Sale Flipbook Countdown": ["Sale Flipbook Countdown","Promo Flipbook (Past Sales Recap)"],
"Video Static (Caption Over Looping B-roll)": ["Video Static (Headline Over Looping B-roll)","Silent POV Caption B-roll","Silent Visual Loop + Long Copy","Tweet Card Over B-roll"],
"Meme Caption Loop": ["Meme Caption Loop","Public Wear Meme Clip","Meme Reaction Split","Status Flex POV"],
"Meme Montage (Chaos Edit)": ["Meme Montage (Chaos Edit)","Found-Footage Meme Montage","Pun Meme Collage","Meme-Page Repost"],
"Micro Bumper (2-6s)": ["Micro Bumper (2-6s)","6-Second Bumper"],
"Offer Stack Breakdown": ["Offer Stack Breakdown","Offer Stack Walkthrough","Offer Stack Escalation ('Wasn't Enough?')"],
"Fit Check (Single Outfit)": ["Fit Check (Silent Outfit Pose)","Fit Check (Single-Outfit OOTD)","Outfit Lookbook POV","Paparazzi Street-Style Clip"],
"Styling Remix (One Piece, Many Looks)": ["One Piece, Many Ways (Styling Remix)","One Item, Many Outfits","Outfit Builder (Flat-Lay to Look)"],
"GRWM (Get Ready With Me)": ["Get Ready With Me (GRWM)","Get Ready With Me (GRWM) Reveal","Family Duo GRWM","Night Routine Romanticize Vlog"],
"Animated Character Story (Pixar / Cartoon)": ["3D Cartoon Character Story","Animated Character Story","3D Animated Story (Pixar-Style)","Animated Cartoon Story","3D Cartoon UGC (Pixar-Style)","Animated Fairy-Tale Storybook","Illustrated Comic Story"],
"AI Cinematic Caption Story": ["AI Cinematic Caption Story"],
"Partner POV (She Sells His Product)": ["Partner POV (Wife/Girlfriend Sells His Product)","Partner Glow-Up (She Fixed Him)","Partner-Observed Testimonial","Send-This-To-Your-Partner Hint"],
"Recipe Reel (Product as Ingredient)": ["Recipe Reel (Product as Ingredient)","Recipe Tutorial (Cook With Me)"],
"Not For Everyone (Reverse Qualifier)": ["Don't-Buy-If Anti-Pitch","Not For Everyone (Reverse Qualifier)"],
"This or That (Pick Your Vibe)": ["This-or-That Picker","This or That (Pick Your Vibe)"],
"Celebrity Spokesperson Spot": ["Celebrity / Pro Spokesperson Spot","Celebrity Spokesperson Selfie","Celebrity Cameo Commercial"],
"Scripted Comedy Sketch": ["Scripted Parody Sketch","Comedic Brand Sketch (Harmon-Style)","Comedy Infomercial (Scripted DRTV Sketch)","Scripted Comedy Sketch (Role-Play)","Scripted Workplace Mini-Skit","In-House Sketch Comedy (Brand Staff Skit)","Meme-Caption Comedy Skit"],
"POV Comedy Skit (Creator Plays the Roles)": ["POV Comedy Montage Skit","Relatable POV Comedy Skit","POV Character Skit","Dual-Role POV Skit","Split-Self Skit (Creator Plays Both Roles)","Couple Banter Skit","Kid Role-Play Skit"],
"Slapstick Old-Way Struggle": ["Slapstick Hard-Way Gag"],
"Absurdist Visual Gag": ["Absurdist Brand Vignette","Surreal Visual Gag"],
"Prank / Versus Skit": ["Prank Skit","Prank Montage (Doing It To Their Stuff)","Versus Battle Skit"],
"IRL Brand Stunt": ["IRL Brand Stunt Recap","Hidden-Camera Public Stunt"],
"Photoshop Fix ('Fixed It For You')": ["Photoshop Fix (Edit-It-For-You)","'Fixed It For You' Edit Swap"],
"Makeover Reveal (Space Transformation)": ["Makeover Reveal (Set-Up Transformation)"],
"Barber-Chair Glow-Up": ["Barber-Chair Glow-Up"],
"Room Tour (Styled Space Walkthrough)": ["Room Tour (Styled Space Walkthrough)","Showroom Walkthrough (Staff Picks)"],
"Mini-Doc Portrait": ["Mini-Doc Athlete/Customer Portrait"],
"Input vs Result Pairs": ["Input vs Result Pairs"],
"Pack My Bag (What's In My Bag)": ["Pack My Bag (What's In My Bag)"],
"Prop Analogy Explainer": ["Prop Analogy Explainer","Stand-In Object Demo","Whiteboard Doodle Explainer"],
"AI Before/After Morph": ["AI Before/After Morph"],
"Usage Timeline Countdown": ["Usage Timeline Countdown","Timestamped POV Session Log","Timestamped Real-Time Test"],
"Behind the Build (Factory / Process Tour)": ["Factory Tour (Behind the Build)","Factory Floor Insider","Numbered Process Steps (How It Works)"],
"YouTube Reviewer Clip (Borrowed Expert)": ["YouTube Reviewer Clip (Borrowed Expert)"],
"BTS vs Final Shot Reveal": ["BTS vs Final Shot Reveal","Behind-the-Scenes Shoot Vlog","Behind-The-Scenes Shoot Vlog"],
"Trade-Show Booth Demo": ["Trade-Show Booth Demo"],
"Product ASMR": ["Product ASMR","ASMR Routine"],
"Review Read-Aloud": ["Review Read-Aloud","Review Quote Montage","Before/After Photo Review Show"],
"IP Collab Drop Trailer": ["IP Collab Drop Trailer"],
"Party Game Play-Along": ["Party Game Play-Along (Branded Edition)","Jubilee-Style Debate Show"],
"Multi-Panel Split Screen": ["Multi-Panel Split Screen","Video Mosaic Grid"],
"In-Store Find (Retail Aisle)": ["Retail Aisle Find","In-Store Find (Retail Aisle Haul)","In-Store Staff Recommendation","Stranger Problem, Store-Run Fix"],
"Quiz Walkthrough": ["Quiz Walkthrough"],
"Panic Restock Reaction": ["Panic Restock Reaction"],
"Jingle / Music Video": ["Jingle Music Video (Sung Product Song)","Song-Vibe Dress Up (Lyric Lip-Sync)"],
"Phone-Screen Investigation": ["Phone-Screen Investigation","Text-Thread Overlay"],
"Torture Test (Try To Break It)": ["Torture Test (Try To Break It)"],
"Occasion Matchmaker": ["Occasion Matchmaker","Week-of-Meals Cost Tally"],
"History Lesson Timeline": ["History Lesson Timeline"],
}
