# Amazon Gerber training pants (redirect B00Q58Q3L6; 6,670 ratings; 82/12/3/1/2 %). Top reviews VERBATIM; Customers-say excerpts SNIPPET.
P="Amazon (Gerber)"; ST="Amazon"; R="https://www.amazon.com/portal/customer-reviews/srp/-/"
ROWS=[
("I like that she feels if she wets herself, as it helps teach her that she just peed. In my opinion, diaper training pants are effective because the child cannot feel when they have an accident ... They really are a great training panty, not diaper.",R+"R3CBUSTT7MLEOE",P,"2016-04-19","5",ST,"VERBATIM","","child learns from feeling wet","feel-wet signal","","Pull-Ups / disposables","","","feeling wet teaches the child; pull-ups hide the wet","Pride","product","","","general toddler parent","a great training panty, not diaper"),
("The prints are so cute, she's always so proud to show me she's wearing them ... which helps her feel more excited about potty training in general, more confident and comfortable with no longer wearing diapers.",R+"R38QQYCUWVI4YL",P,"2021-09-08","5",ST,"VERBATIM","","big-kid underwear feeling; child confidence","fun designs; easy pull up/down","","training underwear (other brand)","","","","Pride","product","","","general toddler parent","so proud to show me she's wearing them"),
("Regular underwear will leave her with completely soaked pants, puddle on the floor, and a footprint trail of pee. SAVE yourself the headache. ... My toddler did not seem to mind if her pull up was wet. She would carry on and not even notice at times. It did not work well for us. These panties make it VERY obvious if she wet her underwear.",R+"R2UDS950IFXZWM",P,"2018-11-03","5",ST,"VERBATIM","laundry / mess; child doesn't notice wet","less mess / cleanup; child learns from feeling wet","feel-wet signal; absorbency that holds a pee","","Pull-Ups / disposables; regular underwear","","","pull-ups hide the wet; feeling wet teaches the child","Pride","product","","","general toddler parent","a footprint trail of pee"),
("They are not leak resistant but I didn't really expect them to be, but wish they were a little more absorbent. However they get the job done for potty training.",R+"R2LYYJQYQPW12Y",P,"2025-11-07","4",ST,"VERBATIM","leaks / soaked after one pee","","absorbency that holds a pee","holds only one small accident","","","","","Neutrality","product","","","general toddler parent",""),
("Some of the reviewers seem confused as to what training underwear is for. ... Putting your child in a pull-up teaches them that accidents are ok if you really don't feel like trying. ... Before I even had my 3 girls, I worked at a daycare for 6 years ... I have personally helped potty train about 30 kids.",R+"R79XN96BX7APH",P,"2013-12-09","5",ST,"VERBATIM","","","feel-wet signal","","Pull-Ups / disposables","","training underwear should catch everything","pull-ups hide the wet; commit and it goes fast","Pride","product","","daycare teacher experience","childcare worker (also parent)","teaches them that accidents are ok"),
("These pants have been a lifesaver during our potty training journey. ... While they don't function like diapers and won't absorb pee ... Even my 2-year-old can easily put them on and take them off independently, which promotes a sense of independence and confidence",R+"R28654TU77OLSW",P,"2024-03-16","5",ST,"VERBATIM","","independence (pull on/off herself)","easy pull up/down","","","","","","Pride","product","","","general toddler parent","a lifesaver during our potty training journey"),
("I like gerber because they soak up most mess and I usually have to clean up is residue or a small puddle vs other brands ive tried and every small potty accident is a huge mess.",R+"RR84VQFLRFW8E",P,"2020-04-15","5",ST,"VERBATIM","laundry / mess","less mess / cleanup","absorbency that holds a pee","","training underwear (other brand)","","","","Pride","product","","","general toddler parent","every small potty accident is a huge mess"),
("Love these! Great for potty training. Better than the regular big girl panties because they catch a good amount of the urine if there is an accident....",R+"R2YB34FWSX24B2",P,"","",ST,"SNIPPET","","less mess / cleanup","absorbency that holds a pee","","regular underwear","","","","Pride","product","","","general toddler parent",""),
("super cute on my little 2 yr old and works great for potty training. she loves her \"big girl\" panties.. they absorb well too, rest easy moms!",R+"R2GAUYF7ZAPXTQ",P,"","",ST,"SNIPPET","","big-kid underwear feeling","absorbency that holds a pee","","","","","","Pride","product","","","general toddler parent","rest easy moms"),
("These are very cute and have a nice thickness about them. They have really helped her potty train as she can feel when she starts to wet.",R+"RJXGKPVYMZIWY",P,"","",ST,"SNIPPET","","child learns from feeling wet","feel-wet signal","","","","","feeling wet teaches the child","Pride","product","","","general toddler parent",""),
("In addition, they are soft, comfy and absorbent. Half the battle of potty training is wanting them to want to wear panties and these do the trick.",R+"RUXZJWKTVIIU",P,"","",ST,"SNIPPET","child refuses underwear","child wants to wear them","fun designs; soft","","","","","","Pride","product","","","general toddler parent","Half the battle of potty training"),
("They work as expected and are pretty absorbent. If your child is a heavy sleeper and pees in their sleep, the bed will get wet however....",R+"R16UMANDHW01RW",P,"","",ST,"SNIPPET","leaks / soaked bed at night","dry bed / sleep","leakproof at night","","","","","","Neutrality","product","","","night / bedwetting parent",""),
("Cons: Sized way too big, buy one or two sizes smaller. Not absorbent - pee goes straight through....",R+"RJ42W14ODAJES",P,"","",ST,"SNIPPET","leaks / soaked after one pee; sizing / fit","","absorbency that holds a pee; consistent sizing","won't hold pee / leaks; sizing uncertain","training underwear (Gerber)","","","","Anger","product","","","general toddler parent","pee goes straight through"),
("for my daughter trying to stop her for wearing pull-ups and they work great you just have to make sure you buy the vinyl covers to put over them.",R+"R3QX0JYE0NJLNF",P,"","",ST,"SNIPPET","","off pull-ups","waterproof cover layer","","Pull-Ups / disposables","","","","Pride","solution","","","general toddler parent","buy the vinyl covers"),
("These panties work great and absorb a small amount of pee but the couch will still get wet.",R+"R1D8IF67T11PZ0",P,"","",ST,"SNIPPET","leaks / soaked after one pee","","absorbency that holds a pee","holds only one small accident","","","","","Neutrality","product","","","general toddler parent","the couch will still get wet"),
("Yet don't help avoid leaks. Terrible purchase. Waste of money. Pretty disappointed coming from such a big brand name.",R+"R1D23VT9PLEOWN",P,"","",ST,"SNIPPET","leaks / soaked after one pee","","absorbency that holds a pee","waste of money; big brand let down","training underwear (Gerber)","","","","Anger","product","waste of money","","general toddler parent",""),
("My daughter loves them. The only downside is when she does have an accident it still leaks quite a bit. Mainly when she has to go a lot.",R+"R3LU88LKHIUILU",P,"","",ST,"SNIPPET","leaks / soaked after one pee","","absorbency that holds a pee","holds only one small accident","","","","","Neutrality","product","","","general toddler parent",""),
("A little big (height wise) but the only kind she can pull up herself! Soft and catches a little wetness so there's no floor puddles.",R+"R10G10OQEU6KM8",P,"","",ST,"SNIPPET","","independence (pull on/off herself); less mess / cleanup","easy pull up/down","","","","","","Pride","product","","","general toddler parent","the only kind she can pull up herself"),
("Perfected fit , she loves them nice and thick do not shrink in dyer at times I put plastic rubber pants on time as we travel in case of a acid...",R+"RW8JRYVCOLYSO",P,"","",ST,"SNIPPET","outings / public accidents","protection out in public","waterproof cover layer","","","","","","Pride","product","","","general toddler parent",""),
]
