# YouTube comments via yt-dlp (Playwright headless hit "Sign in to confirm you're not a bot") — VERBATIM text from YouTube comment API, dates approximate (YouTube relative "N years ago").
ST="YouTube comments"
def U(v,c): return f"https://www.youtube.com/watch?v={v}&lc={c}"
A="LrrpnP_9qAM"; P1="YouTube (How I Potty Trained My Son with Autism)"
B="8AncJYKFS-Y"; P2="YouTube (Truth About Diapers and Pull Ups)"
C="UWYN_MBf-t4"; P3="YouTube (Potty training issues with daycare and preschool)"
D="a6Qm6mQgqZk"; P4="YouTube (Mistake That Turns a Regression Into an Ongoing Problem)"
ROWS=[
("my son is 9 years old he is non verbal  and still not potty trained he still get alot of anxiety about it but i take him when see he needs to use it we just keep trying",U(A,"UgzNMF5D38ie_UCAEFV4AaABAg"),P1,"~2022 (approx)","",ST,"VERBATIM","long timeline / not trained at school age","","","","","","","every kid own timeline","Acceptance","problem","","","ND / sensory parent","we just keep trying"),
("My son is almost 8yrs old, Non-verbal level 3. And it has been up and down. And this has been legitimately the first, \"older boy neurodiverse/autistic potty training\" video that I've seen.",U(A,"UgwsmGNvWbvdw2YOPVh4AaABAg"),P1,"~2023 (approx)","",ST,"VERBATIM","long timeline / not trained at school age; no resources for older kids","help for older kids","resources for older / ND kids","","","","","","Desire","problem","","creator with lived experience","ND / sensory parent","older boy neurodiverse/autistic potty training"),
("Our son is non verbal and he is now 13, we've been trying since he was 4, it's only getting worse, he tears off his diapers and pees on everything, the floor, our furniture ... we're just at our very wits end. I've tried so so so many things, I just wish something would work.",U(A,"Ugwz16PpdnyOief0nUx4AaABAg"),P1,"~2024 (approx)","",ST,"VERBATIM","long timeline / not trained at school age; parent burnout; laundry / mess","something that works","","","tried everything","","","nothing works","Apathy","problem","tried everything","","ND / sensory parent","at our very wits end"),
("I'm so glad I found your video because just 1-2 minutes in and I already feel like a better mom. We don't have a diagnosis yet but there are a lot of signs.",U(A,"Ugzx3rQBd7wnoC-DK9d4AaABAg"),P1,"~2024 (approx)","",ST,"VERBATIM","parent guilt","feel like a good parent","","","","","","","Guilt","problem","","creator with lived experience","ND / sensory parent","I already feel like a better mom"),
("I'll take him to the bathroom before school he'll sit but wont use until the second I pull up his pull up then he will let lose. ... For me its very discouraging cause it makes me feel like I'm doing something wrong but I know he wont go until he's ready",U(A,"UgzVEuTibjKJdj1QuQV4AaABAg"),P1,"~2023 (approx)","",ST,"VERBATIM","child holds until pull-up on; parent guilt","","","","Pull-Ups / disposables","","","readiness matters","Guilt","problem","","creator with lived experience","ND / sensory parent","makes me feel like I'm doing something wrong"),
("He is 5 years old and we have been on a potty trained drill for about a strong year now. ... This video gave me some relief ... as opposed to feeling defeated as a Parent",U(A,"UgzJGeJcR-2yvsznVEJ4AaABAg"),P1,"~2025 (approx)","",ST,"VERBATIM","withholding / poop refusal; parent guilt","relief / patience","","","","started kindergarten","","readiness matters","Guilt","problem","","creator with lived experience","ND / sensory parent","feeling defeated as a Parent"),
("the state of Massachusetts does not provide us with the proper diapers if they do it is very cheap and falls apart so you are forced to buy quality diapers ... it does put a huge damp in my pockets. I am exhausted.",U(A,"Ugx5-pfMc_WVVDbYfFB4AaABAg"),P1,"~2023 (approx)","",ST,"VERBATIM","cost / money drain; size / big-kid products","","bigger sizes; affordable","price","Pull-Ups / disposables","","","","Apathy","problem","","","ND / sensory parent","I am exhausted"),
("I have a level 2 verbal autistic son who is 10 years old and he will pee in the potty but won't poop in the potty. He screams and cries if we make him sit for 2 min. ... I think I need to take him to the toilet every hour but that is exhausting with no help.",U(A,"UgxB9j3P_yQEv0KzgN54AaABAg"),P1,"~2023 (approx)","",ST,"VERBATIM","withholding / poop refusal; parent burnout","","","","Pull-Ups / disposables","","","","Apathy","problem","","","ND / sensory parent; withholding parent","exhausting with no help"),
("I have a 13 old non verbal son ... I try the bathroom and it wasn't working but now I kno its wen he ready so I do it more now cause I was bout to give up",U(A,"UgwqA6eLVH25mx6nhe94AaABAg"),P1,"~2023 (approx)","",ST,"VERBATIM","long timeline / not trained at school age","","","","","","","readiness matters","Willingness","problem","","creator with lived experience","ND / sensory parent","I was bout to give up"),
("attempts at potty training have been going on for like two or three years. ... His preschool and I jusr both try to sit him on the potty at least a couple of times a day...and just as we start getting it I'll get busy again with other kids, husband, whatever, and forget.",U(A,"Ugy0zCYnSglaL8DzWPl4AaABAg"),P1,"~2024 (approx)","",ST,"VERBATIM","consistency hard for busy parent; long timeline","","routine / reminder system","","","","","","Apathy","problem","","","ND / sensory parent; working parent / daycare","we'll keep on plugging"),
("I'm so relieved from the pressure of the immediate need to potty train her because we were told that some schools in our area will only accept kids that are potty trained.",U(A,"UgwmOgMhbsPg8AsLZXR4AaABAg"),P1,"~2023 (approx)","",ST,"VERBATIM","deadline pressure (daycare/school rule)","school-ready without pressure","","","","school requires potty trained","","","Fear","problem","","creator with lived experience","grandparent / gift buyer; ND / sensory parent","only accept kids that are potty trained"),
("Still doesnt make a lot of sense to use pull ups. As a parent you gotta train your kid to use the toilet not 'when they show you they are ready'.",U(B,"Ugxxqkr8BO2Yj96q1TR4AaABAg"),P2,"~2024 (approx)","",ST,"VERBATIM","","","","","Pull-Ups / disposables","","readiness is an excuse","pull-ups are just diapers","Pride","solution","","","general toddler parent","Still doesnt make a lot of sense to use pull ups"),
("Diapers are easier to change than pull-ups especially if they go potty #2.",U(B,"UgyHhTXggKv-YTR64s94AaABAg"),P2,"~2024 (approx)","",ST,"VERBATIM","poop accidents messy","","","","Pull-Ups / disposables","","","","Neutrality","solution","","","general toddler parent",""),
("for a kid that is totally potty trained in the daytime and wears undies then-- are we screwing up by continuing to let him wear actual diapers at nighttime? ... I feel like we're kind of in a minority by having an almost 5 year old still wearing (size 7!) diapers overnight.",U(B,"UgyKxUny9ltUgD4EFZl4AaABAg"),P2,"~2023 (approx)","",ST,"VERBATIM","night wetting; size / big-kid products","dry nights","bigger sizes","","diapers at night","","","","Guilt","solution","","","night / bedwetting parent; single parent","are we screwing up"),
("My 3 1/2 year old daughter has been potty trained for a long time now ... but suddenly having accident almost everyday at preschool. ... I have no idea how to deal with this.",U(C,"UgwGRJKNlocxsRN4H594AaABAg"),P3,"~2025 (approx)","",ST,"VERBATIM","daily accidents at school/daycare; regression","","","","","accidents at preschool","","","Fear","problem","","","working parent / daycare; regression parent","accident almost everyday at preschool"),
("My 4 1/2 year old is not fully potty trained. She goes to daycare, she is the only one who still isn't trained. They put pull ups on her for nap time. ... She's been at the daycare for 1 year and still doesn't tell them when she needs to go.",U(C,"UgyBIlODVAQfpzgyJ454AaABAg"),P3,"~2023 (approx)","",ST,"VERBATIM","daycare vs home inconsistency; comparison to peers","consistent at daycare","daycare-friendly","","Pull-Ups / disposables","","","","Fear","problem","","daycare staff","working parent / daycare; late-trainer parent","she is the only one who still isn't trained"),
("I find it difficult to time her since I am looking after her infant brother. I am really worried because next year she will be going to the daycare. Any parent out there like me?",U(D,"UgyoaRRzkgKnYbaDHPF4AaABAg"),P4,"~2023 (approx)","",ST,"VERBATIM","deadline pressure (daycare/school rule); new sibling","daycare-ready","","","","starting daycare; new sibling","","","Fear","problem","","","working parent / daycare; regression parent","Any parent out there like me?"),
("since his turned 3 he just leaves it too late to go to the potty or refuses and now prefers to be wet in his clothes or becomes secretive when he's had an accident ... I'm running out of trousers because I have to keep washing so much",U(D,"UgznonU3WMM5LX-Y7jN4AaABAg"),P4,"~2025 (approx)","",ST,"VERBATIM","regression; laundry / mess","","","","","","","","Apathy","problem","","","regression parent","running out of trousers"),
("after one full month of going to the potty she now absolutely refuses and continues to go on herself. There has been no big changes. It's so frustrating",U(D,"Ugz8FOo8CcY0xbrO3sB4AaABAg"),P4,"~2025 (approx)","",ST,"VERBATIM","regression; child refuses","","","","","","","","Anger","problem","","","regression parent","It's so frustrating"),
("after a poop incident during the night started to regress and get psychologic constipulation. ... We play games, explain, encourage but there is no effect.",U(D,"UgyIe4XjQuejW5fFxZh4AaABAg"),P4,"~2023 (approx)","",ST,"VERBATIM","withholding / poop refusal; regression","","","","rewards / games","","","","Fear","problem","nothing works","","withholding parent; regression parent","there is no effect"),
("What to do if 3 year old flat out refuses. ... Bribes or rewards are not working. I'm lost.",U(D,"Ugz9oS9JmKEz9vkhGYd4AaABAg"),P4,"~2024 (approx)","",ST,"VERBATIM","child refuses","","","","rewards / stickers / bribes","","","","Apathy","problem","nothing works","","late-trainer parent","I'm lost"),
("when my son started to regress with bowl movements there were no changes....and the regression has gotten WORSE. and we cant get into our dr for over a month",U(D,"UgyWSQx4bpw_-_4drLx4AaABAg"),P4,"~2024 (approx)","",ST,"VERBATIM","regression; withholding / poop refusal; can't access doctor","","","","","","","","Fear","problem","","pediatrician","regression parent; withholding parent","can't get into our dr"),
("As a first time mom who will return to 40 hour work weeks in a little bit, im trying to figure out how to best space my time to make the most of it with my daughter",U(D,"UgwWAtv1uQSxGi93F2h4AaABAg"),P4,"~2023 (approx)","",ST,"VERBATIM","limited time (working parent)","train before back to work","","","","going back to work","","","Desire","problem","","","working parent / daycare","return to 40 hour work weeks"),
]
