# TikTok comments — Playwright headless + Firecrawl scrape both blocked (login wall / "we do not support this site"); comment text taken from firecrawl_search result excerpts = SNIPPET. Dates only where the excerpt prints them right after the comment.
ST="TikTok comments"; P="TikTok"
ROWS=[
("I find it daunting when I work a full time job on how I'm going to properly potty train my son.","https://www.tiktok.com/@applesauceandadhd/video/7271368492396449066",P,"","",ST,"SNIPPET","limited time (working parent)","","","","","","","","Fear","problem","","","working parent / daycare","I find it daunting when I work a full time job"),
("my son was almost 5 when he finally was fully potty trained and he'll be 9 in December and still pees the ...","https://www.tiktok.com/@jess.spaulding/video/7669937477909630239",P,"","",ST,"SNIPPET","long timeline / not trained at school age; daily accidents at school age","","","","","","","","Apathy","problem","","","late-trainer parent; school-age accidents parent",""),
("My son has been potty trained for about 6 weeks. He recently started pooping in his ...","https://www.tiktok.com/@itspottytime_/video/7142911192296656171",P,"","",ST,"SNIPPET","regression; poop accidents messy","","","","","","","","Fear","problem","","potty-training creator","regression parent",""),
("My son will be 3 in April and is around 33lbs and dont have his chuncky legs anymore. Should I go for a large do you think?","https://www.tiktok.com/@gracevcolson/video/7512519194936642847",P,"2026-01-28","",ST,"SNIPPET","sizing uncertainty","","sizing guidance / easy exchange","sizing uncertain","","","","","Desire","product","","influencer review","general toddler parent","Should I go for a large"),
("what are strategies to use instead? we are trying to start this process with our 4 year old with ASD.","https://www.tiktok.com/@theautismconsultant/video/7660925980894039327",P,"2026-08-03","",ST,"SNIPPET","no resources for older / ND kids","method that fits my child","resources for older / ND kids","","","","","methods don't work for ND kids","Desire","solution","","autism consultant","ND / sensory parent; late-trainer parent",""),
("My daughter is still wetting pull ups at 6.5.","https://www.tiktok.com/@mamaot_shannon/video/7614904405795654925",P,"2026-09-16","",ST,"SNIPPET","night wetting","dry nights","","","Pull-Ups / disposables","","","","Neutrality","problem","","OT creator","night / bedwetting parent",""),
("This have me crying like a baby I have a 3 year old ...","https://www.tiktok.com/@ohlanaa/video/7186123953562340650",P,"","",ST,"SNIPPET","","","","","","","","","Grief","problem","","creator with lived experience","ND / sensory parent","crying like a baby"),
("I have ND kiddos and two of them toilet trained laaaaate. I'm not lazy but I'm also not going to traumatise my kid just for society.","https://www.tiktok.com/@turtlecoop/video/7691866893644303647",P,"~2026-10-03","",ST,"SNIPPET","judgment / shame from others","no-pressure process","","","","","late training = lazy parenting","every kid own timeline; no shame approach","Pride","problem","","","ND / sensory parent","I'm not lazy"),
("im using pull ups because no diaper was fitting correctly anymore. he doesn't care about being wet... i need help.","https://www.tiktok.com/@itspottytime_/video/7239808096078712110",P,"2023","",ST,"SNIPPET","size / big-kid products; child doesn't notice wet","","feel-wet signal; bigger sizes","","Pull-Ups / disposables","diaper size outgrown","","pull-ups hide the wet","Fear","solution","","potty-training creator","late-trainer parent","he doesn't care about being wet"),
("\"JuSt PoTtY tRaIn HiM.\" ... Disposable training pants or pull ups just work like bigger diapers ...","https://www.tiktok.com/@soapboxshae/video/7135209486519749934",P,"","",ST,"SNIPPET","judgment / shame from others","","","","Pull-Ups / disposables","","just potty train him","pull-ups are just diapers","Anger","solution","","","late-trainer parent","JuSt PoTtY tRaIn HiM"),
("Underwear is the best way in my opinion. Pull ups are too much like a diaper.","https://www.tiktok.com/@dzaslavsky/video/7541114497142918430",P,"2025-08-21","",ST,"SNIPPET","","","","","Pull-Ups / disposables","","","pull-ups are just diapers","Pride","solution","","","general toddler parent","Pull ups are too much like a diaper"),
("Ok but how are we cleaning 💩 with training pants cuz that's a disaster.","https://www.tiktok.com/@tiktokkiddoc/video/7283992787312282926",P,"2023-10-11","",ST,"SNIPPET","poop accidents messy","","easy poop cleanup","poop cleanup","","","","","Fear","solution","","pediatrician (TikTok)","general toddler parent","that's a disaster"),
("Even if it takes some time for him to \"potty train\", it's so worth it to me!!","https://www.tiktok.com/@thebriellabelle/video/7506700736328240415",P,"2025-05-22","",ST,"SNIPPET","","","","","","","","every kid own timeline","Acceptance","product","","influencer review","general toddler parent",""),
("My son was potty trained in 3 days when he was 19 months old and pooping was the easy ...","https://www.tiktok.com/@caitlynjones/video/7475810043074563374",P,"","",ST,"SNIPPET","","","","","","","3 days is enough","","Pride","solution","","","general toddler parent",""),
]
