# Forums (What to Expect, Mumsnet, BabyCenter) — firecrawl_search excerpts 2026-10-06 (SNIPPET)
ST="Forum"
W="What to Expect"; M="Mumsnet"; B="BabyCenter"
ROWS=[
("We are planning to start potty training April baby right after Thanksgiving, and I am trying to figure out the best training pants.","https://community.whattoexpect.com/forums/april-2025-babies/topic/potty-training-pants-176998698.html",W,"","",ST,"SNIPPET","","","","","","holiday break / planned start","","","Desire","solution","","other parents","working parent / daycare","right after Thanksgiving"),
("my little one has been potty trained for a while now but still quite often has small leaks. anyone else have the same and any advice?","https://community.whattoexpect.com/forums/may-2021-babies/topic/potty-trained-but-still-has-small-leaks-160134740.html",W,"","",ST,"SNIPPET","small leaks after training","","absorbency for dribbles","","","","","","Fear","problem","","other parents","general toddler parent","still quite often has small leaks"),
("If their concern is more about having to clean up accidents, what about those underwear that will prevent leaks but still let the child feel ...","https://community.whattoexpect.com/forums/july-2023-babies/topic/potty-training-when-daycare-requires-pull-ups-174006652.html",W,"","",ST,"SNIPPET","daycare rules on pull-ups/underwear","","feel-wet signal; daycare-friendly","","Pull-Ups / disposables","daycare requires pull-ups","","feeling wet teaches the child","Willingness","solution","","other parents","working parent / daycare","Potty training when daycare requires pull ups"),
("Has anyone found training pants that look and feel like underwear but would hold at least one pee? Thank you!","https://community.whattoexpect.com/forums/march-2023-babies/topic/leakproof-training-underwear-172255924.html",W,"","",ST,"SNIPPET","","real-underwear look with protection","absorbency that holds a pee; real-underwear feel","","training underwear (generic)","","","","Desire","solution","","other parents","general toddler parent","hold at least one pee"),
("Put them in regular undies with a normal nappy on top. They'll feel the wetness of the undies but you won't have the mess on the floor.","https://community.whattoexpect.com/forums/potty-training/topic/diaperspull-ups-that-let-child-feel-wet-174465002.html",W,"","",ST,"SNIPPET","","less mess / cleanup","feel-wet signal; layered protection","","","","","feeling wet teaches the child","Neutrality","solution","","other parents","general toddler parent (UK)",""),
("In my experiences training pants/underwear are not very absorbent at all, and can easily leak . They are good for little dribbles of pee.","https://community.whattoexpect.com/forums/hot-topics-1/topic/nh-training-pants-instead-of-pullups-170231312.html",W,"","",ST,"SNIPPET","leaks / soaked after one pee","","absorbency that holds a pee","holds only one small accident","training underwear (generic)","","","","Neutrality","solution","","","general toddler parent","good for little dribbles of pee"),
("Almost 3 1/2 was unwilling to potty train but all week has been asking to wear underwear. We've been putting him in underwear and he's only had a few accidents.","https://community.whattoexpect.com/forums/may-2023-babies.html",W,"","",ST,"SNIPPET","","child-led readiness","","","","child asks for underwear","","readiness matters","Pride","problem","","","late-trainer parent","asking to wear underwear"),
("They are not waterproof, but delay the accident from wetting down everything instantly! We also use \"rubber pants\" - basically plastic underwear","https://community.whattoexpect.com/forums/june-2023-babies/topic/training-underwear-173014176.html",W,"","",ST,"SNIPPET","","buys time to reach potty","absorbency that holds a pee; waterproof cover layer","","","","","","Neutrality","solution","","","general toddler parent","delay the accident from wetting down everything"),
("I think they work a little better than the other training underwear that I've tried. They leak, but a lot less than others.","https://community.whattoexpect.com/forums/march-2024-babies/topic/upairy-for-potty-training-176464278.html",W,"","",ST,"SNIPPET","leaks / soaked after one pee","","absorbency that holds a pee","holds only one small accident","training underwear (generic)","","","","Neutrality","product","","","general toddler parent","They leak, but a lot less than others"),
("I'm wondering if I should put her in underwear and put a pull up on top of that so she can feel when she's wet but won't make a mess?","https://community.whattoexpect.com/forums/the-toddler-years/topic/potty-training-questions-173285228.html",W,"","",ST,"SNIPPET","","less mess / cleanup","feel-wet signal; layered protection","","","","","feeling wet teaches the child","Desire","solution","","","general toddler parent","feel when she's wet but won't make a mess"),
("PS don't get disposable pull ups, they are not the same, they advertise themselves as training pants but they are just nappies and the child ...","https://www.mumsnet.com/talk/potty_training/2622313-training-pants",M,"","",ST,"SNIPPET","","","","","Pull-Ups / disposables","","","pull-ups are just diapers","Pride","solution","","other parents","general toddler parent (UK)","they are just nappies"),
("He's been in them for over a year as he was such a wriggler we never got his nappies on properly and he leaked, so we found pull ups much better ...","https://www.mumsnet.com/talk/potty_training/5182527-nursery-wont-help-with-pants-is-this-normal?flipped=1&page=1",M,"","",ST,"SNIPPET","daycare rules on pull-ups/underwear","","","","","nursery won't help with pants","","","Neutrality","solution","","nursery staff","working parent / daycare","Nursery won't help with pants"),
("We've never had a leak with Dry Nites, but have a leak every single time we use Huggies pull ups.","https://www.mumsnet.com/talk/potty_training/5271397-nighttime-different-expectations-with-nappies-vs-pull-ups",M,"","",ST,"SNIPPET","leaks / soaked bed at night","dry nights","leakproof at night","","Pull-Ups / disposables","","","","Neutrality","product","","","night / bedwetting parent","a leak every single time"),
("Pull-ups are a marketing gimmick and are simple nappies under another name. They will not help train your child- I speak as a very experienced ...","https://www.mumsnet.com/talk/potty_training/1412338-first-time-at-training-and-I-am-so-confused-pull-ups-or-not",M,"","",ST,"SNIPPET","","","","","Pull-Ups / disposables","","","pull-ups are just diapers","Pride","solution","","experienced childcarer","childcare worker","a marketing gimmick"),
("Disposable pull-ups didn't work for us as DS just used them like a nappy but we didn't have that problem with the BB training pants.","https://www.mumsnet.com/talk/potty_training/891877-waterproof-pants-for-training",M,"","",ST,"SNIPPET","","","washable / reusable","","Pull-Ups / disposables","","","pull-ups are just diapers","Pride","product","","","general toddler parent (UK)","just used them like a nappy"),
("Cloth training pants good imo, DCs think they are normal pants, feel wet like normal pants, but the bit of plastic in the gusset area prevents a ...","https://www.mumsnet.com/talk/parenting/700411-Training-pants-worth-it-or-not",M,"","",ST,"SNIPPET","","real-underwear look with protection","feel-wet signal; real-underwear feel","","","","","feeling wet teaches the child","Pride","solution","","","eco / cloth parent","think they are normal pants"),
("Straight to pants. Mine treated training pants and pull ups as nappies. They were much better bare bum at home","https://www.mumsnet.com/talk/potty_training/1381190-Training-pants-worth-getting-or-waste-of-money",M,"2012-01-11","",ST,"SNIPPET","","","","not needed","training underwear (generic); Pull-Ups / disposables","","","","Neutrality","solution","","","general toddler parent (UK)","treated training pants and pull ups as nappies"),
("There are night pull-ups specifically for this age range: Ninjamas or Huggies night pants, which look more like pants than nappies.","https://www.mumsnet.com/talk/potty_training/5548590-night-time-pull-ups-for-older-child-recommendations-pros-and-cons",M,"","",ST,"SNIPPET","night wetting; size / big-kid products","dignity / looks like pants","discreet; bigger sizes","","","","","","Neutrality","product","","","night / bedwetting parent","look more like pants than nappies"),
("Definately the underwear and no pull ups. They should be used to cleaning up some accidents.","https://community.babycenter.com/post/a34949605/pullups_vs_underwear_at_daycare_when_potty_training_update_on_last_page",B,"","",ST,"SNIPPET","daycare rules on pull-ups/underwear","","daycare-friendly","","Pull-Ups / disposables","","","","Pride","solution","","","working parent / daycare",""),
("His underwear was the same pair I put on him that morning, so I know he didn't have an accident. I talked to one of the teachers on Friday ...","https://community.babycenter.com/post/a41894923/daycare_putting_potty_trained_kid_in_pull_ups",B,"","",ST,"SNIPPET","daycare vs home inconsistency","","daycare-friendly","","","daycare puts trained kid in pull-ups","","","Anger","problem","","","working parent / daycare",""),
("Even if he is fully potty trained and can hold it and go only every hour she says she has to watch him have dry pull-ups for 2 weeks before she ...","https://community.babycenter.com/post/a39257932/daycare_insists_on_pull-ups._advice_needed_please._thank_you",B,"","",ST,"SNIPPET","daycare rules on pull-ups/underwear","","daycare-friendly","","Pull-Ups / disposables","daycare requires pull-ups","","","Anger","problem","","daycare staff","working parent / daycare","dry pull-ups for 2 weeks"),
("I would invest in cloth trainers that have enough absorbency to hold one accident.","https://community.babycenter.com/post/a34201795/daycare_demands_pull-ups_what_to_do",B,"","",ST,"SNIPPET","daycare rules on pull-ups/underwear","","absorbency that holds a pee; daycare-friendly; washable / reusable","","","daycare requires pull-ups","","","Willingness","solution","","other parents","working parent / daycare","enough absorbency to hold one accident"),
("My daycare is apparently no help because all they said is if she keeps having accidents she needs to be put back in pull ups or diapers.","https://community.babycenter.com/post/a69353852/help-almost-fully-potty-trained-at-home-but-not-in-public-and-daycare",B,"","",ST,"SNIPPET","daycare vs home inconsistency; daily accidents at school/daycare","","daycare-friendly","","Pull-Ups / disposables","daycare threatens back to pull-ups","","","Anger","problem","","","working parent / daycare","put back in pull ups or diapers"),
("Our preschool doesn't allow any pullups. It's underpants only, children must be independently toilet trained before preschool starts.","https://community.babycenter.com/post/a43666348/preschooler_and_pull_ups",B,"","",ST,"SNIPPET","deadline pressure (daycare/school rule)","","daycare-friendly","","","preschool rule","","","Neutrality","problem","","","working parent / daycare","underpants only"),
("It was always more of a fight, so we threw in the towel and let it go, went back to pull ups. Then one night DS just decieded he wanted to go","https://community.babycenter.com/post/a53576563/ready_to_throw_in_the_towel_on_potty_training.",B,"","",ST,"SNIPPET","power struggle","child-led readiness","","","Pull-Ups / disposables","","","readiness matters","Apathy","problem","","","late-trainer parent","threw in the towel"),
("I would recommend against going back to Pull-Ups if she does fine at home. Pull-Ups for partial days was causing my ODS to revert back","https://community.babycenter.com/post/a25305541/my_dd_keeps_having_pee_accidents_at_preschool",B,"","",ST,"SNIPPET","daily accidents at school/daycare; regression","","","","Pull-Ups / disposables","accidents at preschool","","pull-ups cause regression","Neutrality","solution","","","working parent / daycare; regression parent","causing my ODS to revert back"),
]
ROWS += [
("The problem is that your child isn't bothered about the feeling of being wet/soiled, this can be a sign of sensory processing issues etc so worth going back to ...","https://www.mumsnet.com/talk/education/5485471-school-said-it-might-be-best-if-ds-is-put-back-in-nappies?page=4",M,"","",ST,"SNIPPET","child doesn't notice wet; daily accidents at school/daycare","","feel-wet signal","","","school says back to nappies","","","Neutrality","problem","","other parents","ND / sensory parent; school-age accidents parent","isn't bothered about the feeling of being wet"),
("Putting him back in nappies does seems retrograde step but if it makes life a little bit easier for now so be it.","https://www.mumsnet.com/talk/education/5485471-school-said-it-might-be-best-if-ds-is-put-back-in-nappies?flipped=1&page=12",M,"","",ST,"SNIPPET","daily accidents at school/daycare","","","","diapers / nappies","school says back to nappies","","","Acceptance","problem","","other parents","school-age accidents parent","retrograde step"),
]
