# Walmart reviews — search snippets (SNIPPET) + BIG ELEPHANT review page scraped VERBATIM 2026-10-06 (839 ratings, 7% 1-star)
ST="Walmart"
W="https://www.walmart.com/reviews/product/209907642"
ROWS=[
("These are really durable and have reinforcement in the crotch area to stop leaks. They are really absorbent and a great next steps from training pants.","https://www.walmart.com/reviews/product/18462802726?page=2","Walmart (Hanes)","","",ST,"SNIPPET","","next step after pull-ups","absorbency that holds a pee; durable / washable","","Pull-Ups / disposables","","","","Pride","product","","","general toddler parent","great next steps from training pants"),
("Cute designs and they do fit as they should. However they are definitely not \"leak-proof\" as it states in the description.","https://www.walmart.com/reviews/product/19593557548","Walmart (generic 4-pack)","","",ST,"SNIPPET","leaks / soaked after one pee","","absorbency that holds a pee","won't hold pee / leaks; ads overpromise","training underwear (generic)","","","ads overpromise","Anger","product","","","general toddler parent","definitely not \"leak-proof\""),
("leak threw as bad into clothes, fit is perfect size, beautiful material, and works like you would expect, easy to change, easy to pull down and pull up","https://www.walmart.com/reviews/product/15016901089","Walmart (Celivon)","","",ST,"SNIPPET","","independence (pull on/off herself)","easy pull up/down","","","","","","Pride","product","","","general toddler parent",""),
("Unfortunately, because of his size and the amount of liquid output, these leaked very easily onto his clothes. Though they offer these in larger sizes, i would ...","https://www.walmart.com/reviews/product/209907642","Walmart (BIG ELEPHANT)","","",ST,"SNIPPET","leaks / soaked after one pee; size / big kid output","","absorbency that holds a pee; bigger sizes","won't hold pee / leaks","training underwear (BIG ELEPHANT)","","","","Grief","product","","","late-trainer / big-kid parent","the amount of liquid output"),
("potty training pants so cute and they are leak proof but they can tell when their wet,well made with good materials","https://www.walmart.com/reviews/product/20214873024","Walmart (BIG ELEPHANT)","","",ST,"SNIPPET","","child learns from feeling wet","feel-wet signal; absorbency that holds a pee","","","","","feeling wet teaches the child","Pride","product","","","general toddler parent","they can tell when their wet"),
("Child can feel the wetness of an accident or a leak before getting to potty but the leak proof layer keeps outside of undies and clothes dry! super soft and ...","https://www.walmart.com/reviews/product/792455978","Walmart (Insular)","","",ST,"SNIPPET","","child learns from feeling wet; less mess / cleanup","feel-wet signal; waterproof cover layer","","","","","feeling wet teaches the child","Pride","product","","","general toddler parent","keeps outside of undies and clothes dry"),
("I was looking for the old fashion underwear thick ones . These are thick and I like it . Because if he does have an accident ? The thickness will capture the fluids .",W,"Walmart (BIG ELEPHANT)","2023-08-03","5",ST,"VERBATIM","","holds an accident","absorbency that holds a pee","","","","","","Pride","product","","","grandparent / gift buyer","the old fashion underwear thick ones"),
("When he pees, it stays in the underwear and doesn't get all over the place. They are super soft!",W,"Walmart (BIG ELEPHANT)","2022-11-18","5",ST,"VERBATIM","","less mess / cleanup","absorbency that holds a pee","","","","","","Pride","product","","","general toddler parent",""),
("the 1st set is still going strong, and they have faded very little considering the massive amount of washes.",W,"Walmart (BIG ELEPHANT)","2025-06-05","5",ST,"VERBATIM","","reusable / lasts","durable / washable","","","","","","Pride","product","","","general toddler parent","massive amount of washes"),
("did not hold pee at all",W,"Walmart (BIG ELEPHANT)","2025-07-07","1",ST,"VERBATIM","leaks / soaked after one pee","","absorbency that holds a pee","won't hold pee / leaks","training underwear (BIG ELEPHANT)","","","","Anger","product","","","general toddler parent",""),
("It is not as absorbent as advertised. It leaks through when the child pees.",W,"Walmart (BIG ELEPHANT)","2026-07-10","1",ST,"VERBATIM","leaks / soaked after one pee","","absorbency that holds a pee","won't hold pee / leaks; ads overpromise","training underwear (BIG ELEPHANT)","","","ads overpromise","Anger","product","","","general toddler parent","Not absorbent as advertised"),
]
