# UPSTREAM wave (2026-10-06, after the §11 lock): school-age (5–9) DAYTIME accident snippets for the locked market
# "Big kids still learning". Collected via firecrawl_search (Reddit / What to Expect / BabyCenter / Mumsnet / Facebook groups,
# all SNIPPET = search-result text), yt-dlp YouTube comments (VERBATIM), Amazon /dp/ "Customers say" excerpt (SNIPPET).
# File name starts with "new_z" so it sorts AFTER the wave-1 files and the existing N001–N264 IDs do not shift.
# Buyer-group rule: "school-age accidents parent" ONLY when the poster is a parent/carer describing their own child aged
# ~5–9 with DAYTIME accidents. Commenters giving advice = "commentator"; teachers = "school teacher".
# Reddit dates: estimated from the base-36 post ID with the same anchor table as convert_old.py (INFERENCE).
import re
from convert_old import reddit_date
ROWS=[]
def R(q,url,plat,date="EST",stars="",src="Reddit",cap="SNIPPET",pain="",desire="",need="",objection="",failed="",trigger="",
      misc="",belief="",emo="Neutrality",aw="problem",burned="",auth="",bg="",gp=""):
    if date=="EST":
        m=re.search(r"/comments/([a-z0-9]+)/",url)
        date=reddit_date(url) if int(m.group(1),36)>=int("3ii3ei",36) else "before 2015-08 (est. from post ID)"
    ROWS.append((q,url,plat,date,stars,src,cap,pain,desire,need,objection,failed,trigger,misc,belief,emo,aw,burned,auth,bg,gp))
SA="school-age accidents parent"; ND="ND / sensory parent"
U="https://www.reddit.com/r/"
# ---------------- Reddit ----------------
R("My son is 7. He is in second grade. He regularly comes home from school with wet pants or underwear.",U+"pottytraining/comments/1gansad/my_7_year_old_wets_his_pants_regularly/","Reddit r/pottytraining",pain="daily accidents at school/daycare",bg=SA,gp="comes home from school with wet pants or underwear")
R("It started with bedwetting but it has progressed to frequent accidents during the day, too.",U+"Parenting/comments/3xw6q6/my_6_yo_son_wont_stop_peeing_his_pants/","Reddit r/Parenting",pain="constant accidents; night wetting",emo="Fear",bg=SA)
R("My 7 year old also struggles with this. We've seen both a pediatric urologist and gastroenterologist, had multiple x-rays and ultrasounds done",U+"Parenting/comments/1bf3nj/8_year_old_girl_still_wetting_during_the_day_tips/","Reddit r/Parenting",pain="constant accidents",failed="Miralax / medical",emo="Apathy",aw="solution",auth="pediatric urologist",bg=SA)
R("And I would really lay off any effort to shame her about this. I can guarantee you that no 8 year old wants to be wetting her pants.",U+"Parenting/comments/1bf3nj/8_year_old_girl_still_wetting_during_the_day_tips/","Reddit r/Parenting",belief="no shame approach",emo="Courage",aw="problem",bg="commentator",gp="no 8 year old wants to be wetting her pants")
R("My daughter was still having daytime accidents at school",U+"Parenting/comments/162h8ap/anyone_have_a_kid_that_had_accidents_at_6_years/","Reddit r/Parenting",pain="daily accidents at school/daycare",bg=SA)
R("Anyone have a kid that had accidents at 6 years old that eventually figured it out? Potty-training. Our 6 year old daughter still wears pull-ups",U+"Parenting/comments/162h8ap/anyone_have_a_kid_that_had_accidents_at_6_years/","Reddit r/Parenting",pain="late training (3.5y+ still not trained)",failed="Pull-Ups / disposables",emo="Fear",bg=SA,gp="eventually figured it out")
R("I am thinking your daughter can't help it because the social stigma of constantly peeing your pants in first grade is enough to where she",U+"Parenting/comments/162h8ap/anyone_have_a_kid_that_had_accidents_at_6_years/","Reddit r/Parenting",pain="child shame / embarrassment",belief="child can't help it",emo="Acceptance",bg="commentator",gp="the social stigma of constantly peeing your pants in first grade")
R("I asked about why a child would need pelvic floor PT and she said that it's mostly for bed wetting and accidents in general.",U+"Parenting/comments/162h8ap/anyone_have_a_kid_that_had_accidents_at_6_years/","Reddit r/Parenting",aw="solution",auth="pelvic floor PT",bg=SA)
R("We ended up having him go in the morning before school and immediately upon getting home.",U+"Parenting/comments/1h8hvv0/6_year_old_son_wont_stop_peeing_pants/","Reddit r/Parenting",need="routine / reminder system",aw="solution",emo="Willingness",bg=SA)
R("Since 3 years old, she's only gone approximately one week without having any accidents during the day or at night.",U+"pottytraining/comments/1vmn4jp/please_help_my_55_year_old_is_still_wetting/","Reddit r/pottytraining",pain="constant accidents; late training (3.5y+ still not trained)",emo="Grief",bg=SA)
R("Here's the deal : my 7 year old daughter randomly wets her pants. Exclusively day wetting. No bed wetting ever. Relatively new issue.",U+"breakingmom/comments/cad7uz/7_year_wetting_her_pants/","Reddit r/breakingmom",pain="regression; constant accidents",emo="Fear",bg=SA,gp="Exclusively day wetting")
R("Now I am wondering if I need to buy pull-ups again just so she's not having accidents at school.",U+"Parenting/comments/1vmmxhw/please_help_my_55_year_old_is_still_wetting/","Reddit r/Parenting",pain="daily accidents at school/daycare",desire="daycare/school-ready",failed="Pull-Ups / disposables",trigger="accidents at school",emo="Fear",aw="solution",bg=SA,gp="buy pull-ups again just so she's not having accidents at school")
R("We went through a period with my then 7 year old because he was having constant accidents and once we solved the constipation",U+"Parenting/comments/5c1kt3/8_year_old_having_accidents/","Reddit r/Parenting",pain="constant accidents",belief="constipation causes accidents",aw="solution",emo="Acceptance",bg=SA)
R("Can you ask her to start sending the 8 year old out to go to the bathroom a few times a day. (S)he can phrase it as \"going to the nurse\".",U+"Parenting/comments/5c1kt3/8_year_old_having_accidents/","Reddit r/Parenting",need="routine / reminder system; discreet",aw="solution",bg="commentator")
R("He was perfectly trained before and doesn't have any accidents outside of school - genuinely last day time pee accident he was maybe 20 months?",U+"kindergarten/comments/1ade6zl/kindergarten_several_accidents_a_day_what_to_do/","Reddit r/kindergarten",pain="daily accidents at school/daycare; regression",trigger="school start (K/Reception)",emo="Fear",bg=SA,gp="doesn't have any accidents outside of school")
R("My son started kindy in August and the first week was great. However, since then, he's been having constant accidents.",U+"kindergarten/comments/1ade6zl/kindergarten_several_accidents_a_day_what_to_do/","Reddit r/kindergarten",pain="daily accidents at school/daycare",trigger="school start (K/Reception)",emo="Fear",bg=SA)
R("Kindergartener has accidents daily, if not multiple times a day. Its definitely time to talk to your pediatrician.",U+"kindergarten/comments/1kac79i/help_were_at_our_wits_end_kindergartener_has/","Reddit r/kindergarten",pain="daily accidents at school/daycare",auth="pediatrician",aw="problem",bg="commentator",gp="time to talk to your pediatrician")
R("Teacher needs to stop teaching/ helping other children, take your child to bathroom, make sure he is in clean clothes, put wet clothes in a bag",U+"kindergarten/comments/1mmjiql/daily_pee_accidents/","Reddit r/kindergarten",pain="judgment / shame from others",trigger="school/teacher complaint",emo="Anger",bg="commentator")
R("Constantly/Regularly wetting oneself at 5 is NOT normal or common. It is either a medical issue or a behavioral issue.",U+"kindergarten/comments/1jhhtc1/how_often_do_your_kids_have_accidents/","Reddit r/kindergarten",pain="judgment / shame from others",misc="untrained at 5 = severe delay",emo="Anger",bg="commentator")
R("Constipation puts pressure on the bladder, which can interrupt the signals it sends to let the brain know that it's full.",U+"kindergarten/comments/1w07s0g/pee_accidents_in_kindergarten/","Reddit r/kindergarten",belief="constipation causes accidents",aw="solution",bg="commentator")
R("Just to be clear if your child is having accidents that's ok. Very common at that age and we understand that.",U+"AskTeachers/comments/1va5viw/kindergarten_teachers_what_common_factors_are_you/","Reddit r/AskTeachers",belief="no shame approach",emo="Acceptance",bg="school teacher",gp="if your child is having accidents that's ok")
R("Today is the 3rd time my daughter (5years old, kindergarten) has had an accident at school. Last week her teacher sent me a message",U+"Mommit/comments/16dpgv6/5_year_old_having_accidents_at_school/","Reddit r/Mommit",pain="daily accidents at school/daycare",trigger="school/teacher complaint",emo="Fear",bg=SA)
R("My daughter is six now and set to start first grade in the fall. Unfortunately she's still very prone to wetting accidents.",U+"AskParents/comments/w5tzwb/6yo_still_having_accidents_about_to_start_school/","Reddit r/AskParents",pain="constant accidents",trigger="school start (K/Reception)",emo="Fear",bg=SA)
R("A lot of kids regress in potty training when they start school. Stress, new routines, sometimes embarrassment of using public or classroom",U+"AskParents/comments/w5tzwb/6yo_still_having_accidents_about_to_start_school/","Reddit r/AskParents",trigger="school start (K/Reception)",belief="every kid own timeline",bg="commentator")
R("My kindergartner (5.5) has had constant accidents since we started potty training at age 2.5.",U+"kindergarten/comments/1o0ubo9/constant_accidents/","Reddit r/kindergarten",pain="constant accidents; late training (3.5y+ still not trained)",emo="Apathy",bg=SA)
R("My son is 6 now with ADHD. He had no issues with bedtime wetting, but during the day if he isn't reminded and practically pulled from his",U+"Parenting/comments/wokr31/pee_accidents_and_adhd/","Reddit r/Parenting",pain="child doesn't notice wet / body signals",need="routine / reminder system",bg=SA+"; "+ND)
R("In a nutshell, he still has frequent daytime wetting accidents",U+"Incontinence/comments/1b6jqtt/looking_for_advice_about_my_9_yearold_son_who/","Reddit r/Incontinence",pain="constant accidents",emo="Apathy",bg=SA)
R("About 5 months ago, my almost 8 year old started wetting his pants during the daytime. We've done the normal investigations, no physical issues.",U+"ADHDparenting/comments/1capno8/help_daytime_toilet_accidents/","Reddit r/ADHDparenting",pain="regression",failed="Miralax / medical",emo="Fear",bg=SA+"; "+ND)
R("My 6yo son with ADHD is so smart and fun. He's been potty trained since about 3 as normal, but he will on and off struggle with wetting his",U+"ParentingADHD/comments/1l37qjg/6yo_wetting_his_pants/","Reddit r/ParentingADHD",pain="constant accidents",emo="Pride",bg=SA+"; "+ND,gp="so smart and fun")
R("He has multiple pee accidents a day and doesn't seem to notice when he's wet. He wants to wear underwear at night and be dry during the day",U+"ParentingADHD/comments/1ectrja/5_year_old_wets_himself_and_doesnt_care/","Reddit r/ParentingADHD",pain="child doesn't notice wet / body signals; constant accidents",desire="child dignity / real underwear",emo="Desire",bg=SA+"; "+ND,gp="He wants to wear underwear")
R("She might benefit from using liners/pads if it's only a small amount of liquid.",U+"ADHDparenting/comments/1lw2h1r/urine_accident_but_doesnt_change_after_wards/","Reddit r/ADHDparenting",need="discreet; absorbency that holds a pee",aw="solution",bg=ND)
R("Peeing isn't her only sensory issue. She doesn't feel pain the same as most kids, sometimes gets nonverbal or completely non communicative",U+"specialed/comments/1gdqp6g/6_yo_girl_with_adhd_and_some_sort_of_sensory/","Reddit r/specialed",pain="child doesn't notice wet / body signals; sensory discomfort",emo="Fear",bg=SA+"; "+ND)
R("My ADHD kid was the same. It's a common issue. They don't want to break what they are doing. Punishing will not help.",U+"Parenting/comments/10o765u/kids_will_not_stop_pissing_themselves/","Reddit r/Parenting",belief="no shame approach",emo="Acceptance",bg=ND,gp="Punishing will not help")
R("We learned it was a disconnect in his brain being physically aware of his body. He didn't \"feel\" the urge to pee",U+"Autism_Parenting/comments/1b5vv1k/six_year_old_still_pees_pants_at_home/","Reddit r/Autism_Parenting",pain="child doesn't notice wet / body signals",emo="Acceptance",aw="solution",bg=SA+"; "+ND)
R("Benefits vs hazards of sending 7-yr-old to school in pull-ups / He is embarrassed about his accidents, but never seems to try to get better.",U+"Mommit/comments/1ndsyhy/benefits_vs_hazards_of_sending_7yrold_to_school/","Reddit r/Mommit",pain="child shame / embarrassment",failed="Pull-Ups / disposables",emo="Fear",aw="solution",bg=SA,gp="He is embarrassed about his accidents")
R("Just keep working at it, have him wear the pullups under his underwear so his peers don't tease him",U+"Mommit/comments/1ndsyhy/benefits_vs_hazards_of_sending_7yrold_to_school/","Reddit r/Mommit",pain="fear child will be teased",need="discreet",aw="solution",bg="commentator",gp="so his peers don't tease him")
R("I have an 8 year old perfectly fine but he's always having accidents.. Not bad but enough for for his underwear to get dirty. Its disgusting",U+"Mommit/comments/1ndsyhy/benefits_vs_hazards_of_sending_7yrold_to_school/","Reddit r/Mommit",pain="laundry / mess; constant accidents",emo="Anger",bg=SA)
R("we send him to school with extra pants and underwear. this can be a common issue with kids who have ASD.",U+"Autism_Parenting/comments/1gbazs7/almost_6_year_old_level_1_having_increased/","Reddit r/Autism_Parenting",need="spare-clothes kit for school",aw="solution",emo="Acceptance",bg=SA+"; "+ND)
R("My 6 year old will wear undies to school, but she has a long history of severe constipation.",U+"Autism_Parenting/comments/1kmmsun/does_anyone_have_children_over_the_age_of_5_that/","Reddit r/Autism_Parenting",belief="constipation causes accidents",bg=SA+"; "+ND)
R("My 7 year old level 3 son was day trained at 5. I switched to underwear hoping for the best and it worked. I think he was just ready.",U+"Autism_Parenting/comments/1uk1p91/what_age_was_your_autistic_child_potty_trained/","Reddit r/Autism_Parenting",belief="readiness matters",emo="Pride",aw="solution",bg=SA+"; "+ND,gp="I switched to underwear hoping for the best")
R("It's common for autistic individuals to have issues with interoception, and that includes the feeling of needing to pee.",U+"Autism_Parenting/comments/1h1u34f/6_year_old_forgetting_to_pee/","Reddit r/Autism_Parenting",pain="child doesn't notice wet / body signals",aw="solution",bg="commentator")
R("Underwear seem to be a sensory nightmare to him, but he wears them at school no problem.",U+"Autism_Parenting/comments/1kum93p/did_it_take_a_long_time_after_potty_training_for/","Reddit r/Autism_Parenting",pain="sensory discomfort",need="sensory-friendly fit",bg=ND,gp="a sensory nightmare")
R("The training pants are good because they can soak up the pee enough so clean ups aren't too bad.",U+"Autism_Parenting/comments/1pzq5d3/has_training_pants_worked_for_potty_training_with/","Reddit r/Autism_Parenting",desire="less mess / cleanup",need="absorbency that holds a pee",emo="Pride",aw="product",bg=ND)
R("Mine peed in her pants in 1st grade (she was 7 and hadn't done that",U+"kindergarten/comments/1mnmryw/my_kid_peed_herself_first_day_of_school/","Reddit r/kindergarten",pain="regression",bg=SA)
R("Pants Wetting. My son is actually 7 and in first grade.",U+"kindergarten/comments/1j2z4cq/pants_wetting/","Reddit r/kindergarten",pain="constant accidents",bg=SA)
R("When, at his 1st grade teacher's request due to numerous accidents, we told my son he would be starting a bathroom schedule at school",U+"Parenting/comments/1c7am3v/my_5yo_almost_6_keeps_peeing_at_school/","Reddit r/Parenting",pain="daily accidents at school/daycare",need="routine / reminder system",trigger="school/teacher complaint",aw="solution",bg=SA)
R("My daughter is scared to ask to go to the bathroom at school (6yrs",U+"Parenting/comments/ty1hms/my_daughter_is_scared_to_ask_to_go_to_the/","Reddit r/Parenting",pain="child afraid to ask at school",emo="Fear",bg=SA,gp="scared to ask to go to the bathroom at school")
R("I distinctly remember a girl in my 1st grade class being made fun of for it and the teacher screaming at her after an accident.",U+"Parenting/comments/jrs1gq/frequent_potty_accidents_in_kindergarten/","Reddit r/Parenting",pain="fear child will be teased",emo="Fear",bg="commentator")
R("I'm a first grade teacher and. We send extra clothes and she keeps them in her backpack and changes herself if she has one … both pee and poop",U+"kindergarten/comments/1gobdc0/son_keeps_having_potty_accidents/","Reddit r/kindergarten",need="spare-clothes kit for school",desire="independence (pull on/off herself)",aw="solution",auth="daycare teacher experience",bg="school teacher")
R("Showed him the extra clothes in his backpack, which are inside a “wet bag” and told him that if he has an accident, he changes into the dry",U+"kindergarten/comments/1mmvmyx/prepping_kiddo_who_struggles_with_potty_accidents/","Reddit r/kindergarten",need="spare-clothes kit for school",desire="independence (pull on/off herself)",trigger="school start (K/Reception)",emo="Courage",aw="solution",bg=SA,gp="inside a “wet bag”")
R("He just tells the teacher and goes to his backpack to get his extra clothes",U+"kindergarten/comments/1rt6rb5/diapers/","Reddit r/kindergarten",need="spare-clothes kit for school",desire="independence (pull on/off herself)",emo="Pride",aw="solution",bg=SA)
R("In an ideal situation, he'd wear a pull-up that he can change",U+"kindergarten/comments/1rt6rb5/diapers/","Reddit r/kindergarten",desire="independence (pull on/off herself)",failed="Pull-Ups / disposables",aw="solution",bg="commentator")
R("My then first grader was having SO many accidents and it took",U+"kindergarten/comments/1frt9ze/only_a_few_weeks_in_but_having_lots_of_accidents/","Reddit r/kindergarten",pain="constant accidents",emo="Fear",bg=SA)
R("The Dr thinks it was caused by constipation issues. I just always kept spare clothes in a separate bag in their backpack.",U+"kindergarten/comments/1nifuup/potty_accidents/","Reddit r/kindergarten",need="spare-clothes kit for school",belief="constipation causes accidents",auth="pediatrician",aw="solution",bg=SA)
R("I just had conferences and reminded all my first graders' parents to please send extra clothes in their backpack.",U+"Teachers/comments/636i18/bathroom_accidents_what_is_your_schools_policy/","Reddit r/Teachers",need="spare-clothes kit for school",bg="school teacher")
R("We use the goodnites nighttime underwear, much thinner than regular diapers/pull ups and I put a pair of regular underwear on top to conceal the",U+"kindergarten/comments/1o2oybe/alternative_to_pull_ups/","Reddit r/kindergarten",need="discreet; real-underwear look with protection",failed="Goodnites",aw="product",bg=SA,gp="regular underwear on top to conceal")
R("Pull-ups also help the child. Pack lots of extra pants.",U+"AskTeachers/comments/1qhqrh9/kindergarten_and_pull_ups/","Reddit r/AskTeachers",need="spare-clothes kit for school",aw="solution",bg="school teacher")
R("I know he feels embarrassed about it already and is so afraid his classmates will find out he still has accidents and still wears a pull up",U+"Parenting/comments/15b1ati/i_am_at_my_wits_end_over_this_my_six_almost_7/","Reddit r/Parenting",pain="child shame / embarrassment; fear child will be teased",failed="Pull-Ups / disposables",emo="Grief",bg=SA,gp="so afraid his classmates will find out")
R("Low stakes teasing and embarrassment over things the child can change like still wearing diapers as a 7 year old",U+"Teachers/comments/1dbsgw4/a_child_in_year_1_is_still_not_toilettrained_at/","Reddit r/Teachers",pain="judgment / shame from others",misc="late training = lazy parenting",emo="Anger",bg="commentator")
R("We've done most of them with my 8 year old (who still struggles due to ADHD at times).",U+"Preschoolers/comments/1l3kzfm/regular_pee_accidents_due_to_fomo/","Reddit r/Preschoolers",failed="tried everything",emo="Acceptance",aw="solution",bg=SA+"; "+ND)
R("I have an 8 year old who had a similar problem. I set alarms on my phone and for about a",U+"daddit/comments/10nyc6f/my_9_yo_admits_to_purposefully_wetting_themselves/","Reddit r/daddit",need="routine / reminder system",aw="solution",bg=SA+"; dad")
# ---------------- Forums (What to Expect / BabyCenter / Mumsnet / Facebook groups) ----------------
W="https://community.whattoexpect.com/forums/"
R("I have tried SO SO many things to get her to stop the accidents. We've done Miralax (per doctors advice), re-potty training several times",W+"hot-topics-1/topic/5-year-old-still-having-accidents-146705310.html","What to Expect (Hot Topics)",date="n/d",src="Forum",pain="constant accidents; parent burnout",failed="Miralax / medical; tried everything",emo="Apathy",aw="solution",burned="tried everything",auth="pediatrician",bg=SA,gp="I have tried SO SO many things")
R("My son started a new school September and throughout the year he was having in and off pee accidents. I brought it up to the dr",W+"february-2021-babies/topic/5-year-old-still-having-accidents-176058594.html","What to Expect (February 2021 Babies)",date="n/d",src="Forum",pain="daily accidents at school/daycare",trigger="school start (K/Reception)",auth="pediatrician",bg=SA)
R("I have a 6 year old daughter who is in 1st grade. 2 days in a row she has come home wet from school because she had an accident.",W+"november-2017-babies/topic/1st-grade-accidents-at-school-teacher-input.html","What to Expect (November 2017 Babies)",date="n/d",src="Forum",pain="daily accidents at school/daycare",emo="Fear",bg=SA,gp="come home wet from school")
R("Have you tried to talk to the school about making things work for him? Like someone can take him to the bathroom? They need to accommodate him.",W+"april-2018-babies/topic/potty-anxiety-and-accidents-at-school-159344623.html","What to Expect (April 2018 Babies)",date="n/d",src="Forum",need="school accommodation",aw="solution",bg="commentator")
B="https://community.babycenter.com/post/"
R("They said that the vast, vast majority of daytime wetting issues is due to a combo of 2 things: constipation",B+"a29790219/7_years_old_and_still_having_accidents","BabyCenter Community",date="n/d",src="Forum",belief="constipation causes accidents",auth="pediatric urologist",aw="solution",bg=SA)
R("My oldest was a late potty trainer and still wets at night. During the last few weeks, he has been having daytime accidents again too.",B+"a70517233/6-year-old-potty-regression","BabyCenter Community",date="n/d",src="Forum",pain="regression; late training (3.5y+ still not trained); night wetting",emo="Fear",bg=SA)
R("She usually just has some wetness but occassionally full accidents that seep through her pants. We go to Ped Urologist the end of this month.",B+"a38915014/7_year_old_peeing_pants_during_the_day","BabyCenter Community",date="n/d",src="Forum",pain="leaks / soaked after one pee",need="absorbency that holds a pee",auth="pediatric urologist",bg=SA,gp="full accidents that seep through her pants")
R("My 5 Year old Son wets his pants almost every day. Most of the time only once but sometimes twice a day too. I am constantly reminding",B+"a32451381/5_year_old_wets_his_pants_almost_daily?page=3","BabyCenter Community",date="n/d",src="Forum",pain="constant accidents; parent burnout",need="routine / reminder system",emo="Apathy",bg=SA,gp="I am constantly reminding")
R("He has nighttime accidents, so he wears pull-ups only at nighttime, but he never has accidentally wet himself fhroughout the day. Anyhow, he did",B+"a54907054/my_five_year_old_just_started_peeing_himself_during_the_daytime.","BabyCenter Community",date="n/d",src="Forum",pain="regression",emo="Fear",bg=SA)
M="https://www.mumsnet.com/talk/"
R("6 year old ds came home today having had two wetting accidents at school. He had one last week.",M+"_chat/4893871-is-it-normal-for-6-year-old-to-still-wet-themselves","Mumsnet",date="n/d",src="Forum",pain="daily accidents at school/daycare",emo="Fear",bg=SA)
R("I called the ERIC helpline and they were a great help and advised me to help him increase his fluid intake. Doesn't work.",M+"parenting/3098602-End-of-my-tether-with-7-year-old-wetting-himself","Mumsnet",date="n/d",src="Forum",pain="parent burnout",failed="Miralax / medical",emo="Anger",aw="solution",burned="nothing works",auth="continence charity (ERIC)",bg=SA,gp="End of my tether")
R("my son is 8 and has suddenly started wetting himself at school.",M+"childrens_health/5208363-help-why-has-my-son-started-wetting-himself","Mumsnet",date="n/d",src="Forum",pain="daily accidents at school/daycare; regression",emo="Fear",bg=SA)
R("Lots of 5 and 6 year olds have have accidents.",M+"am_i_being_unreasonable/2757701-To-be-fed-up-with-5yo-wetting-himself-DAILY","Mumsnet",date="n/d",src="Forum",belief="every kid own timeline",emo="Acceptance",bg="commentator")
R("I have a son in year one who wets himself at school most days and never tells anyone when this has happened.",M+"primary/1170802-Any-advice-on-wetting-at-school-age-6","Mumsnet",date="n/d",src="Forum",pain="daily accidents at school/daycare; child can't communicate need",emo="Fear",bg=SA,gp="never tells anyone")
R("He is now 5.5 and in year one and this past week at school he has wet himself 4 times.",M+"childrens_health/2564813-My-son-keeps-wetting-himself-at-school","Mumsnet",date="n/d",src="Forum",pain="daily accidents at school/daycare",bg=SA)
R("He has only been doing half days at the moment and has come out from school most days having either had a accident/slightly wet pants",M+"_chat/3694881-DS-started-reception-and-now-wetting-himself","Mumsnet",date="n/d",src="Forum",pain="daily accidents at school/daycare",trigger="school start (K/Reception)",bg=SA)
R("my son has just gone into year 1 at primary school and every day he is wetting himself.",M+"parenting/4050698-6-year-old-wetting-himself-at-school","Mumsnet",date="n/d",src="Forum",pain="daily accidents at school/daycare",trigger="school start (K/Reception)",emo="Fear",bg=SA)
R("Constipation causes night wetting and also lack of warning in daytime causing accidents. Very common for doctors to miss this",M+"childrens_health/3015326-5yo-daughter-wetting-herself","Mumsnet",date="n/d",src="Forum",belief="constipation causes accidents",burned="skeptical",bg="commentator")
R("Yes it's very common for children to start having accidents when they start school.",M+"primary/1864956-Has-anyone-elses-child-started-having-accidents-after-starting-in-reception","Mumsnet",date="n/d",src="Forum",trigger="school start (K/Reception)",belief="every kid own timeline",emo="Acceptance",bg="commentator")
F="https://www.facebook.com/groups/"
R("If he is having accidents during the day, I'd try a set schedule of going to the bathroom every 2 hours. He may be distracted and wait too long.",F+"2248314252100341/posts/4166949240236823/","Facebook group (ADHD parents)",date="n/d",src="Forum",need="routine / reminder system",aw="solution",bg="commentator")
R("Id suggest use diapers or pull ups to help protect her dignity.",F+"autismparenting/posts/2136127697311541/","Facebook group (Autism Parenting)",date="n/d",src="Forum",desire="child dignity / real underwear",failed="Pull-Ups / disposables",aw="solution",bg="commentator",gp="protect her dignity")
# ---------------- YouTube comments (yt-dlp, VERBATIM) ----------------
Y="https://www.youtube.com/watch?v=f1V_VhGKgwE&lc="
YP="YouTube (What four things should you consider in a daytime wetting child?)"
R("Thanks now I need to find a way to communicate this with my daughters dad! (Which is impossible, it's his way or no way) I know what she needs but he only shames her. She is 8 and now is telling her he is putting diapers on her for when she goes to school! Help!!",Y+"UgwIE5RvMbRDoKYUFQZ4AaABAg",YP,date="~2025 (YouTube '1 year ago')",src="YouTube comments",cap="VERBATIM",pain="judgment / shame from others",trigger="relative judgment",emo="Anger",bg=SA,gp="he only shames her")
R("My 5 year old daughter does this everyday and it seems to be getting worse, I was the exact same way",Y+"UgyH6Po8pAksxnJJ0y94AaABAg",YP,date="~2024 (YouTube '2 years ago')",src="YouTube comments",cap="VERBATIM",pain="constant accidents",emo="Fear",bg=SA)
R("Sir my girl is 5 years but she doesn't wet on bed but when she is awake praying or at school she wets in her pands am always busy with work",Y+"Ugw4ERDIPMCBPhHIeFV4AaABAg",YP,date="~2024 (YouTube '2 years ago')",src="YouTube comments",cap="VERBATIM",pain="daily accidents at school/daycare; limited time (working parent)",bg=SA)
R("My son has told me that he doesn't want to pee his pants at school because someone might say something. He appears to have ADHD-level inattentiveness",Y+"UgzbaR7pcCjXaz_RwM14AaABAg.9pT2GgRUGQz9q972akqLm1",YP,date="~2023 (YouTube '3 years ago')",src="YouTube comments",cap="VERBATIM",pain="fear child will be teased; child doesn't notice wet / body signals",emo="Fear",bg=SA+"; "+ND,gp="because someone might say something")
# ---------------- Amazon (big-size listing, "Customers say" Fit excerpt, star not shown) ----------------
R("I love that the sizes go up even more. I'd say they're true to size he's 6, and the size 6 fit great and have fun design choices.","https://www.amazon.com/portal/customer-reviews/srp/-/R2C8EJI2LTHABE","Amazon (MooMoo Baby 9T listing B0CZ34MF49)",date="n/d",src="Amazon",need="bigger sizes; fun designs",emo="Pride",aw="product",bg=SA,gp="I love that the sizes go up even more")
