# Trustpilot UpAiry page 1 — scraped VERBATIM 2026-10-06 via firecrawl_scrape https://www.trustpilot.com/review/upairy.com
# fields: quote,url,platform,date,stars,source_type,capture,pain,desire,need,objection,failed_solution,trigger,misconception,belief,emotional_state,awareness_stage,burned_skeptical,authority_trusted,buyer_group,great_phrase
P="Trustpilot (UpAiry)"; ST="Trustpilot"; T="https://www.trustpilot.com/reviews/"
ROWS=[
("Amazing customer service! I wasn't sure the size of training pants and so I ordered mediums and a few large but these work very well and she's just about finished potty training so I don't think we will have to move her up a size.",T+"6ac436d1b4fa8f301a2380f5",P,"2026-10-04","5",ST,"VERBATIM","sizing uncertainty","out of diapers / independence","sizing guidance / easy exchange","sizing uncertain","","","","","Pride","product","","","general toddler parent",""),
("Subscription scam, do not use this company, wish I had read more of these reviews before purchasing. I think most of the positive reviews are also fake and by bots. ... I think this is a scam company targeting tired and busy parents through social media. Truly awful.",T+"6ac3e951868b837e4b76371f",P,"2026-10-05","1",ST,"VERBATIM","hidden subscription / billing","","honest checkout","scam / hidden subscription","training underwear (UpAiry)","","","fake reviews everywhere","Anger","product","scam","","general toddler parent","targeting tired and busy parents"),
("excited for my order and getting a better experience at potty training my 1 1/2 year old!",T+"6ac3beeb2e97cbdd28b5b256",P,"2026-10-05","5",ST,"VERBATIM","","fun designs kid wants to wear","fun designs","","","","","","Desire","product","","","general toddler parent",""),
("When I ordered the pants I tried getting rid of the 'Free' gummies as I had no interest in them but was unable to order anything without these included. The pants turn out to be useless so a total waste of money and a month in I was charged for more of these gummies I never wanted in the first place.",T+"6ac34d24bff63382399694d8",P,"2026-10-05","1",ST,"VERBATIM","hidden subscription / billing; doesn't hold pee","","honest checkout","scam / hidden subscription; waste of money","training underwear (UpAiry)","","","","Anger","product","scam; waste of money","","general toddler parent","total waste of money"),
("I can say that its very close to an underwear so its very helpful in teaching my child to remove it and put it back on her own. It can hold one tiny accident. ... currently my child doesnt seem to mind the wetness. So if I dont keep checking, I'm worried my child will develop a rash or something.",T+"6ac3265baf4905c878a2f040",P,"2026-10-04","5",ST,"VERBATIM","child doesn't notice wet","independence (pull on/off herself)","easy pull up/down; feel-wet signal","holds only one small accident","","","","","Fear","product","","","general toddler parent","very close to an underwear"),
("I was a little skeptical to order at first but I want to start potty training soon and I wanted to try these after so many positive reviews. My 3yr old is a small baby compared to most and I thought the medium would be perfect but turned out to be big.",T+"6ac2dce59c65257897f2c6bf",P,"2026-10-04","5",ST,"VERBATIM","sizing uncertainty","","sizing guidance / easy exchange","sizing uncertain; skeptical of brand","","about to start training","","reviews from other parents","Desire","product","skeptical","other parents' reviews","general toddler parent","a little skeptical to order"),
("They are made very poorly and sizing is so inconsistent some pairs of the bundle I bought wouldn't even fit my daughter's legs without cutting off circulation. ... the product is not worth the price and cheaper alternatives are the same quality",T+"6ac0c9c433a9a185e4fe3899",P,"2026-10-03","1",ST,"VERBATIM","poor quality / tight elastic","","consistent sizing","not worth the price; quality","training underwear (UpAiry)","","","cheaper alternatives are the same","Anger","product","waste of money","","general toddler parent","cutting off circulation"),
("Unfortunately they were too big ... they still held the \"accident\" well! Had tried cheaper brands for my son and they never worked so thought I'd pay that little bit extra this time for my twins",T+"6ac0a9a1afb0b38c3fba4d09",P,"2026-10-03","5",ST,"VERBATIM","cheap brands don't hold","holds an accident","absorbency that holds a pee","","cheap training underwear","","","you get what you pay for","Pride","product","","","twins parent","cheaper brands ... never worked"),
("I purchased the product and the product did not hold the urine. Both the toddler and I got soaked with urine. ... they appeared to fit but were not at all absorbent.",T+"6abeac4586da8cbb7afbfb4c",P,"2026-09-06","1",ST,"VERBATIM","leaks / soaked after one pee","","absorbency that holds a pee","won't hold pee / leaks","training underwear (UpAiry)","","","","Anger","product","waste of money","","general toddler parent","Both the toddler and I got soaked"),
("Do not use this company! Albeit the pants were average (not great for cost and shipped from China). They scam you through hidden subscriptions! £31 they took unannounced for 1 pack of gummies, madness.",T+"6abe3e09e8a5b3cba0cdf620",P,"2026-10-01","1",ST,"VERBATIM","hidden subscription / billing","","honest checkout","scam / hidden subscription; shipped from China; price","training underwear (UpAiry)","","","","Anger","product","scam","","general toddler parent (UK)",""),
("they appeared to be an Australian company, but the pants are coming from China and take way longer to arrive than expected, secondly, I ordered the largest size but they were still too tight. I'm having to remove all the elastic just so my child can wear them. ... I had been signed up for a monthly subscription without my consent and didn't find out until they charged another $68 a month later!",T+"6abce2aa16b56b25ad75a201",P,"2026-09-30","1",ST,"VERBATIM","size too small; slow shipping; hidden subscription","","bigger sizes; honest checkout","shipped from China; scam / hidden subscription; will leak out the front","training underwear (UpAiry)","","","","Anger","product","scam","","late-trainer / big-kid parent","remove all the elastic"),
("They were not leak proof! After night one we have a soaked bed and I am out $100. Disappointed because I can buy potty training underwear anywhere, but I thought these would be leak proof.",T+"6abbf1ed01f23fee56c08851",P,"2026-09-28","1",ST,"VERBATIM","leaks / soaked bed at night","dry bed","leakproof at night","won't hold pee / leaks; price","training underwear (UpAiry)","soaked bed","leak proof training underwear exists","","Anger","product","waste of money","","night / bedwetting parent","soaked bed and I am out $100"),
("Ordered and got free gummies. Thought it was ok but seems that when you order this you agree to a 40 euro subscription for this. ... Only small letters on the website. A very sneaky scam!",T+"6aba3e394047218ada3bb005",P,"2026-09-28","1",ST,"VERBATIM","hidden subscription / billing","","honest checkout","scam / hidden subscription","","","","","Anger","product","scam","","general toddler parent (EU)","A very sneaky scam"),
("Perfect for potty training. And hold wet in really well.",T+"6ab958d295ba3650cc38cfe7",P,"2026-09-27","5",ST,"VERBATIM","","holds an accident","absorbency that holds a pee","","","","","","Pride","product","","","general toddler parent",""),
("I was told to wash them before use so I did that. They still leak. After one pee in them they're SOAKED! I don't recommend. That's probably why they sell pads for the bed too such a waste of money.",T+"6ab92251c21ad5ffef486dcf",P,"2026-09-27","2",ST,"VERBATIM","leaks / soaked after one pee","","absorbency that holds a pee","won't hold pee / leaks; waste of money","training underwear (UpAiry)","","","","Anger","product","waste of money","","general toddler parent","After one pee in them they're SOAKED"),
("I was, like many, very skeptical but other reviews encouraged me to give them a try and if I was dissastisfied to send them back. No returns for me!",T+"6ab9204db6ac386706c11502",P,"2026-09-22","5",ST,"VERBATIM","","","returns / guarantee","skeptical of brand","","","","reviews + easy returns lower risk","Willingness","product","skeptical","other parents' reviews","general toddler parent","like many, very skeptical"),
("The size I ordered didn't work, and since a larger size wasn't listed online, I reached out ... They immediately offered to send me an XL at no cost ... my toddler absolutely loved the included stickers!",T+"6ab8962d766f2c4749745620",P,"2026-09-13","5",ST,"VERBATIM","size too small","","bigger sizes; sizing guidance / easy exchange","sizing uncertain","","","","","Pride","product","","","general toddler parent",""),
("Got them in about one week. First pair used and leaked right through on the floor. Dissatisfied.",T+"6ab852a94b5cea6d71996bba",P,"2026-09-26","1",ST,"VERBATIM","leaks / soaked after one pee","","absorbency that holds a pee","won't hold pee / leaks","training underwear (UpAiry)","","","","Anger","product","waste of money","","general toddler parent","leaked right through on the floor"),
("We will just be starting and I am sure these will quicken the process. The different designs are very nice.",T+"6ab83789b441afc2b59aa0fd",P,"2026-09-26","5",ST,"VERBATIM","","faster training","fun designs","","","about to start training","special underwear speeds training","","Desire","product","","","general toddler parent","quicken the process"),
]
