# Amazon Hanes Potty Trainer Boxer Briefs (B0BHX8S5J3) + Pampers Easy Ups (B077VKQY65; 1,001 ratings 81/11/4/1/3%) — live scrape 2026-10-06, VERBATIM
ST="Amazon"; R="https://www.amazon.com/portal/customer-reviews/srp/-/"; H="Amazon (Hanes)"; E="Amazon (Pampers Easy Ups)"
ROWS=[
("These are a must have for potty training. The padded part helps with accidents but doesn't work like a diaper. It will absorb some but they still get wet and it helps them understand.",R+"R3E01QE30A0TRU",H,"2025-09-30","5",ST,"VERBATIM","","child learns from feeling wet","feel-wet signal; absorbency that holds a pee","","","","","feeling wet teaches the child","Pride","product","","","general toddler parent","it helps them understand"),
("My son loves these, very easy to put on by himself and take off quick for bathroom breaks.",R+"R2ZELDMES44FOU",H,"2025-07-25","5",ST,"VERBATIM","","independence (pull on/off herself)","easy pull up/down","","","","","","Pride","product","","","general toddler parent",""),
("at naps and bedtime I was using a diaper/pull up to keep me from having to wash bedding. He would pee in them if he wore them but stays dry when he has underwear on. So I had to break away from the pull ups ... not one drop got on his bed. Yes the underwear were wet but it saves from having to wash all the bedding.",R+"R1OZ077GQ7LE3V",H,"2023-05-04","5",ST,"VERBATIM","laundry / mess","dry bed / sleep; off pull-ups","leakproof at night; absorbency that holds a pee","","Pull-Ups / disposables","","","pull-ups hide the wet","Pride","product","","","night / bedwetting parent","stays dry when he has underwear on"),
("We mostly let him run around naked since he can't quite get them all the way up and down on his own ... they save our furniture and floors from major pee puddles. ... I just wanted something to put on him when I sit him down to eat or need to leave the room and do laundry",R+"R33N2OH5IH5AOQ",H,"2023-10-23","5",ST,"VERBATIM","laundry / mess","less mess / cleanup","absorbency that holds a pee","","naked method","","","","Pride","product","","","general toddler parent","save our furniture and floors from major pee puddles"),
("The fabric is incredibly soft, making it comfortable against my 2-year-old's sensitive skin. ... The smooth, comfort-seams are gentle on his skin and minimize irritation. My only concern is that the size runs a bit small",R+"RRGZAHUNE0T4H",H,"2023-08-04","4",ST,"VERBATIM","size too small / tight elastic; sensory discomfort","comfort on sensitive skin","sensory-friendly fit","runs small","","","","","Pride","product","","","ND / sensory parent","gentle on his skin"),
("I've had these for about 2 years now. My toddler wore them to school. He has now outgrown them. The fabric is soft and the lining is thick and absorbent.",R+"R3BFTUFE6V2Z8Z",H,"2025-07-15","5",ST,"VERBATIM","","daycare-approved","absorbency that holds a pee; daycare-friendly; durable / washable","","","","","","Pride","product","","","working parent / daycare","My toddler wore them to school"),
("These underwear hold his pee in of he has an accident. So goodbye to stepping in random wet spots.",R+"R2UA4ZMBLVM699",H,"2025-04-29","5",ST,"VERBATIM","laundry / mess","less mess / cleanup","absorbency that holds a pee","","","","","","Pride","product","","","general toddler parent","goodbye to stepping in random wet spots"),
("Complete waste of money as they leak! I bought them for my 4 year old to help him learn to come out of nappies at night but he went through 2 pairs in the night and it wet the bed. They are most definitely NOT leakproof!","https://www.amazon.com/dp/B0BHX8S5J3","Amazon (Hanes, UK)","2025-07-03","1",ST,"VERBATIM","leaks / soaked bed at night","dry bed / sleep","leakproof at night","won't hold pee / leaks; waste of money","training underwear (Hanes)","","","","Anger","product","waste of money","","night / bedwetting parent","most definitely NOT leakproof"),
("Fit fine at first but get loose after few minutes of wearing and get too loose and leaks go through. Disappointed.","https://www.amazon.com/dp/B0BHX8S5J3","Amazon (Hanes, UAE)","2025-06-27","1",ST,"VERBATIM","leaks / soaked after one pee; sizing / fit","","snug leg fit","won't hold pee / leaks","training underwear (Hanes)","","","","Grief","product","","","general toddler parent",""),
("Game changer for any potty training parent ... I do wish they had some sort of line or cooling sensation to let us and her know if she pees. Sometimes they're so absorbant that I don't realize she's gone in them until after a couple of pees.","https://www.amazon.com/dp/B077VKQY65","Amazon (Pampers Easy Ups, Canada)","2020-11-10","5",ST,"VERBATIM","child doesn't notice wet","","feel-wet signal; wetness indicator","","","","","pull-ups hide the wet","Pride","product","","","general toddler parent","I don't realize she's gone in them"),
("I took off a star though bc it doesn't have a wetness indicator ... These really are an \"alternative\" to underwear as opposed to a pull up version of diapers.","https://www.amazon.com/dp/B077VKQY65","Amazon (Pampers Easy Ups, Canada)","2021-08-31","4",ST,"VERBATIM","","","wetness indicator","","","","","","Neutrality","product","","","general toddler parent",""),
("these are better for potty trained toddlers that are no longer pooping in the pullups.","https://www.amazon.com/dp/B077VKQY65","Amazon (Pampers Easy Ups, Canada)","2023-12-30","4",ST,"VERBATIM","poop accidents messy","","","","Pull-Ups / disposables","","","","Neutrality","product","","","general toddler parent",""),
("My daughter pee's a lot through the night still and huggies shape and absorption just didn't cut it. ... have eliminated night times leaks completely ... I also like they slide on like real underwear, preparing her and I for potty training.","https://www.amazon.com/dp/B077VKQY65","Amazon (Pampers Easy Ups, Canada)","2020-10-15","5",ST,"VERBATIM","leaks / soaked bed at night","dry bed / sleep","leakproof at night","","Pull-Ups / disposables","","","","Pride","product","","","night / bedwetting parent","slide on like real underwear"),
]
