# Reddit batch 2 — firecrawl_search excerpts (SNIPPET) 2026-10-06
ST="Reddit"
def r(s): return "Reddit r/"+s
ROWS=[
("They hold a lot of urine. Kiddo will pee in them with a full bladder before letting us know that they need changed. No leaks. I like them better ...","https://www.reddit.com/r/pottytraining/comments/1jre9lv/upairy_training_pants/",r("pottytraining"),"","",ST,"SNIPPET","","holds an accident","absorbency that holds a pee","","","","","","Pride","product","","","general toddler parent","They hold a lot of urine"),
("For us they Big Elephant work at all - we still had a lot of leaks, especially during the nighttime.","https://www.reddit.com/r/pottytraining/comments/1h4mtuk/potty_training_underwear/",r("pottytraining"),"","",ST,"SNIPPET","leaks / soaked bed at night","","leakproof at night","won't hold pee / leaks","training underwear (BIG ELEPHANT)","","","","Anger","product","","","night / bedwetting parent",""),
("The outside material doesn't even feel waterproof! And the inside absorbant pad seems to be nothing more than a cotton gauze material. Total ...","https://www.reddit.com/r/toddlers/comments/1jx7e4o/upairy_training_pants_review_they_dont_work/",r("toddlers"),"","",ST,"SNIPPET","leaks / soaked after one pee; poor quality","","absorbency that holds a pee","won't hold pee / leaks; quality","training underwear (UpAiry)","","","ads overpromise","Anger","product","waste of money","","general toddler parent","they don't work"),
("I bought them and they aren't leakproof. You might as well save your money and buy training underwear.","https://www.reddit.com/r/pottytraining/comments/1qe1pdc/upairy/",r("pottytraining"),"","",ST,"SNIPPET","leaks / soaked after one pee","","absorbency that holds a pee","won't hold pee / leaks; price","training underwear (UpAiry)","","","","Neutrality","product","waste of money","","general toddler parent","save your money"),
("So for underwear we got the MooMoo training underwear from amazon. Like UpAiry they have a waterproof layer. That said regardless of brand ...","https://www.reddit.com/r/Mommit/comments/1m99fjw/potty_training_underwear/",r("Mommit"),"","",ST,"SNIPPET","","","waterproof cover layer","","","","","","Neutrality","product","","","general toddler parent",""),
("I want to leave the house. So I bought some training pants on Amazon (moomoo baby) and I plan on using them as he does NOT care about wet undies","https://www.reddit.com/r/pottytraining/comments/1e6glss/training_pants_cloth/",r("pottytraining"),"","",ST,"SNIPPET","stuck at home during training; child doesn't notice wet","leave the house","protection out in public","","","cabin fever during training","","","Desire","product","","","general toddler parent","I want to leave the house"),
("I use the Upairy training underwear with my daughter. Not a silver bullet, but I like them better than the cheaper ones from Amazon","https://www.reddit.com/r/pottytraining/comments/1uh7439/upairy_training_pants/",r("pottytraining"),"","",ST,"SNIPPET","","","","","training underwear (other brand)","","","","Neutrality","product","","","general toddler parent","Not a silver bullet"),
("They seem to have too much padding and he doesn't know they are wet. Not to mention that they do in fact leak.","https://www.reddit.com/r/toddlers/comments/1q0cwz6/upairy_fail/",r("toddlers"),"","",ST,"SNIPPET","leaks / soaked after one pee; child doesn't notice wet","","feel-wet signal","won't hold pee / leaks; feels like a diaper","training underwear (UpAiry)","","","pull-ups hide the wet","Anger","product","","","general toddler parent","he doesn't know they are wet"),
("My only complaint is because they are thicker, she sweats a little more in them but it's not a deal breaker for me. She does recognize when ...","https://www.reddit.com/r/pottytraining/comments/1h8ehc6/affordable_leakfree_training_underwear_thats_not/",r("pottytraining"),"","",ST,"SNIPPET","sensory discomfort","","breathable","","","","","","Neutrality","product","","","general toddler parent",""),
("We have a 5 year old who wears a size large in target brand overnight underwear and it's about $19.99 a box.","https://www.reddit.com/r/Autism_Parenting/comments/12l7suj/options_for_diapers_beyond_size_7/",r("Autism_Parenting"),"","",ST,"SNIPPET","cost / money drain; size / big-kid products","","bigger sizes; affordable","price","Pull-Ups / disposables","","","","Neutrality","solution","","","ND / sensory parent",""),
("I know some said it worked within a couple weeks and others say their kid didn't care about feeling wet.","https://www.reddit.com/r/Autism_Parenting/comments/1pzq5d3/has_training_pants_worked_for_potty_training_with/",r("Autism_Parenting"),"","",ST,"SNIPPET","child doesn't notice wet","","feel-wet signal","may not work for my kid","training underwear (generic)","","","","Neutrality","solution","","other parents","ND / sensory parent","didn't care about feeling wet"),
("I like it because it's easier to clean than cotton underwear (for poop accidents), however at the same time I think it actually inhibited potty ...","https://www.reddit.com/r/Autism_Parenting/comments/1vd2to8/potty_training_underwear/",r("Autism_Parenting"),"","",ST,"SNIPPET","poop accidents messy","","easy poop cleanup","may slow training","training underwear (generic)","","","","Neutrality","product","","","ND / sensory parent","easier to clean"),
("Update: We ended up getting Lucky & Me brand underwear and we haven't had any problems since! They are super soft, 100% cotton, ...","https://www.reddit.com/r/Autism_Parenting/comments/1fkc8qk/sensoryfriendly_underwear/",r("Autism_Parenting"),"","",ST,"SNIPPET","sensory discomfort","","sensory-friendly fit","","","","","","Pride","product","","","ND / sensory parent","super soft, 100% cotton"),
("I am currently potty training my 5-year-old. She was diagnosed at 2 years level 3 nonverbal as well. She is now talking and mimicking ...","https://www.reddit.com/r/Autism_Parenting/comments/1n931p9/anyone_elses_3_year_old_still_in_diapers/",r("Autism_Parenting"),"","",ST,"SNIPPET","long timeline / not trained at school age","","","","","","","every kid own timeline","Willingness","problem","","","ND / sensory parent",""),
("I have a non-verbal 5 year old still working on potty training and he wears Goodnights pull-ups. He goes to an ABA school and they did most of ...","https://www.reddit.com/r/Autism_Parenting/comments/1u0q3tm/how_the_heck_do_you_pottytrain_a_nonverbal_child/",r("Autism_Parenting"),"","",ST,"SNIPPET","long timeline / not trained at school age","","bigger sizes","","Goodnites","","","","Neutrality","solution","","ABA therapist","ND / sensory parent",""),
("She wore them when we first started potty training, but she would still have accidents in them (they are thicker but aren't made to hold urine ...","https://www.reddit.com/r/Autism_Parenting/comments/1lfgn15/5_year_old_wont_wear_training_underwear/",r("Autism_Parenting"),"","",ST,"SNIPPET","child refuses product; leaks / soaked after one pee","","absorbency that holds a pee; sensory-friendly fit","won't hold pee / leaks","training underwear (generic)","","","","Neutrality","solution","","","ND / sensory parent","5 year old won't wear training underwear"),
("Do not go back to pull ups. It will make the regression worse. Get training underwear. A kinda that she still feels wet in.","https://www.reddit.com/r/toddlers/comments/1mjj5lk/is_it_time_to_go_back_to_pull_ups/",r("toddlers"),"","",ST,"SNIPPET","regression","","feel-wet signal","","Pull-Ups / disposables","","","pull-ups cause regression; feeling wet teaches the child","Neutrality","solution","","other parents","regression parent","It will make the regression worse"),
("Switching back to pull ups is not a good idea. Is it his teachers or the director/owner that's asking you to bring the pull ups?","https://www.reddit.com/r/pottytraining/comments/d1w9w9/daycare_wants_pull_ups_alternatives/",r("pottytraining"),"","",ST,"SNIPPET","daycare rules on pull-ups/underwear","","daycare-friendly","","Pull-Ups / disposables","daycare requires pull-ups","","pull-ups cause regression","Neutrality","solution","","daycare staff","working parent / daycare","Daycare wants pull ups"),
("Pull ups will only cause potty training to take four times as long and be four times as frustrating.","https://www.reddit.com/r/Parenting/comments/1uqucrb/what_age_did_you_switch_to_pull_up_style_diapers/",r("Parenting"),"","",ST,"SNIPPET","","","","","Pull-Ups / disposables","","","pull-ups are just diapers","Anger","solution","","","general toddler parent","four times as frustrating"),
("If it helps on top of being a toddler mom I'm a toddler teacher with potty trainers I always engorge going back to pull ups for a bit!","https://www.reddit.com/r/toddlers/comments/1hzsssn/at_wits_end_with_this_f_potty_i_cant_take_it/",r("toddlers"),"","",ST,"SNIPPET","parent burnout","","","","Pull-Ups / disposables","","","readiness matters","Acceptance","problem","","daycare staff","childcare worker","At wits end with this f*** potty"),
("We just switched back to pull-ups (ours is 2+8 months now) because he also just doesn't seem to care at all that he's wet, and I'm just done","https://www.reddit.com/r/toddlers/comments/1ny8vek/potty_training_is_killing_me_and_ruining_my/",r("toddlers"),"","",ST,"SNIPPET","parent burnout; child doesn't notice wet; marriage strain","","feel-wet signal","","Pull-Ups / disposables","","","","Apathy","problem","","","general toddler parent","Potty Training is Killing Me and Ruining My Marriage"),
("It's ok to go back to pull ups or diapers for now. Keep the potty stuff out, and she may voluntarily use it even while you're taking a break.","https://www.reddit.com/r/toddlers/comments/1q4gpyj/persevere_or_try_again_later_help/",r("toddlers"),"","",ST,"SNIPPET","","no-pressure process","","","","","","readiness matters","Acceptance","problem","","other parents","general toddler parent","taking a break"),
("I didn't want to go back to pull ups either, and I felt my husband was being lazy for not wanting to clean the underwear.","https://www.reddit.com/r/Parenting/comments/de7r4j/potty_training_not_going_well/",r("Parenting"),"","",ST,"SNIPPET","laundry / mess; marriage strain","","","","Pull-Ups / disposables","","","","Anger","problem","","","general toddler parent","not wanting to clean the underwear"),
]
